### ISSUE TITLE
Change TextInput's icon size

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [akveo/react-native-ui-kitten#10]
The following code does not change the icon's size
```jsx
import {RkTextInput} from 'react-native-ui-kitten';
import Icon from 'react-native-vector-icons/EvilIcons'
    <RkTextInput
      placeholder='Login'
      label={<Icon name="user" size={80}/>}
      rkType="rounded"
    />
```
It always appear as small icon

**Comment by malashkevich** [comment]
Hello @rafaelcorreiapoli.
This happens because `RkTextInput` has default styles for all internal components.
As label is also internal component - it has some default `fontSize` value.
In order to override it you can use inline styling:

```
<RkTextInput
  placeholder='Login'
  label={<Icon name="star"/>}
  labelStyle={{fontSize:80}}
  rkType="rounded"
/>
```
But if you need to maintain styles separately - it's good idea to create new `rkType`. There are some examples in documentation (https://akveo.github.io/react-native-ui-kitten/#/docs/ui-components/rktextinput)
But for exact this sample you can do following:
1. At start of the app define new `rkType`:
```
RkTheme.setType('RkTextInput', 'bigLabel', {
  labelFontSize: 80
});
```
2. Just use this `rkType` in your app:
```
<RkTextInput
  placeholder='Login'
  label={<Icon name="star"/>}
  rkType="rounded bigLabel"
/>
```
Hope it helps.

**Comment by rafaelcorreiapoli** [comment]
Thanks!
