### ISSUE TITLE
5.0.0 Upgrade

### ISSUE THREAD

**Issue by kev2316** [akveo/react-native-ui-kitten#1081]
## 💬 Question

How big of an impact of an update will it be going from 4.4.1  to 5.0.0
Just curious because I recently implemented this at a base level. And if this is going to be implemented here as an example, I will update as soon as I can. I am getting a very strange error when upgrading to 5.0.0. Slightly surprised it happens as it seems to be an internal error, but I am sure it is because I was using 4.4.1. Regardless the error is as follows for reference to my questions.
`Unable to resolve "./card/cardHeader.component" from "node_modules/@ui-kitten/components/ui/index.js"`

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0     |
| @ui-kitten/components   |   5.0.0      |

**Comment by artyorsh** [comment]
> How big of an impact of an update will it be going from 4.4.1 to 5.0.0

Please see a [changelog](https://github.com/akveo/react-native-ui-kitten/blob/master/CHANGELOG.md) and [release highlights](https://github.com/akveo/react-native-ui-kitten/issues/517)

> Unable to resolve "./card/cardHeader.component"

This is a common caching problem. See https://github.com/akveo/react-native-ui-kitten/issues/997

> And if this is going to be implemented here as an example, I will update as soon as I can.

Missed that when transferring from Kitten Tricks.
Can't focus on it right now, so I will not say it will not be updated soon.

However, I suggest you [migrating](https://akveo.github.io/react-native-ui-kitten/docs/migration/4x500-migration#4x--500-ui-kitten-migration) since the list of closed issues is not small and, as you say, you've just implemented the library into your project.
