### ISSUE TITLE
Change Styling of React Native Date picker

### ISSUE THREAD

**Issue by presola** [akveo/react-native-ui-kitten#1089]
## 💬 Question
I would like to change the styling of my React Native Date Picker, I want to remove the background and the border, how do I do that ?

## UI Kitten and Eva version
| @ui-kitten/components   |  5   |

**Comment by artyorsh** [comment]
@presola which background do you want to remove? Of input field?
If this case is only specific for one place in your app, you can use [mapping customization feature](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping#customize-component-mapping). Otherwise, if it is repeated in other places - [Branding](https://akveo.github.io/react-native-ui-kitten/docs/guides/branding#branding)

**Comment by presola** [comment]
@artyorsh , is there a way to change the date picker to show the maximum date as default rather than today's date
