### ISSUE TITLE
componentWillMount() is deprecated

### ISSUE THREAD

**Issue by B4UGUYS** [akveo/react-native-ui-kitten#112]
Hello guys, I found the following warning.How can I fix this?
YellowBox.js:80 Warning: isMounted(...) is deprecated in plain JavaScript React classes. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.

Thanks.

**Comment by artyorsh** [comment]
Hi @B4UGUYS,
We're sorry for late reply.
Looks like your issue is linked [here](https://github.com/facebook/react-native/issues/18868). If you take a look at it, you'll see, that this is a core RN issue which was fixed in 0.56.0
Btw, currently we're using latest expo fork of React Native and there are no warnings like this.
Thanks for your reply!
