### ISSUE TITLE
Can't run UI Kitten in new or existing project

### ISSUE THREAD

**Issue by charcho1** [akveo/react-native-ui-kitten#1124]
Hello,
I am trying to incorporate UI Kitten into an existing app. I am following the instructions outlined https://akveo.github.io/react-native-ui-kitten/docs/guides/getting-started#new-apps, but receive the following errors. Could you please advise?

![image](https://user-images.githubusercontent.com/17416681/83441038-b9a57000-a3fa-11ea-906b-91b213dcecc4.png)

I have also tried to run UI Kitten in a brand new app following the instructions in the above hyperlink. I type in npm run android, and receive the following errors.  Clearing watchman watches as advised did not solve the problem. Do I need to have yarn installed to use UI Kitten? I prefer using Expo without Yarn as I found Yarn to be quite buggy with an android emulator (doesn't open on emulator properly). 

Thanks for your help!

![image](https://user-images.githubusercontent.com/17416681/83441439-61bb3900-a3fb-11ea-85e1-3dc8fd517c15.png)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

**Comment by artyorsh** [comment]
Please take attention on the warnings printed to the console. You're missing `react-native-svg` package. This is also mentioned in the guide you refer.

Please note you should use `expo install react-native-svg` instead of `npm install`.

But according to the attached screenshot it's more likely you're missing all of the dependencies. Did you run `npm install`?
