### ISSUE TITLE
Question: This UI Kit work with react js?

### ISSUE THREAD

**Issue by ImAbhishekTomar** [akveo/react-native-ui-kitten#1141]
Question: This UI Kit work with react js?

**Comment by artyorsh** [comment]
You may run it with React Native Web, in case you're interested in web solutions.

**Comment by andersravn** [comment]
I had the idea of making a React.js version of the library. Both because we need it for our web projects (using UI Kitten for our Expo apps) and as a learning experience into OSS and library authoring. The probability of me actually following through on this is little. But I wanted to know if the maintainers of UI Kitten/Akveo had any thoughts/considerations/recommendations regarding this?
