### ISSUE TITLE
Avoid keyboard dismiss select item

### ISSUE THREAD

**Issue by adscud** [akveo/react-native-ui-kitten#1163]
## 💬 Question

Is there a way to prevent the keyboard from closing when we select an item from the select?

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^2.0.0-alpha.1    |
| @ui-kitten/components   |    ^5.0.0-alpha.1     |

**Comment by artyorsh** [comment]
Could you please explain the entire workflow of that? May be with recording a short video so I can understand that.
Select component shouldn't open keyboard itself, since it doesn't require manual input.

**Comment by ArthurDelbeke** [comment]
The problem does not come from the select itself, but elsewhere in my code. Sorry! :)

**Comment by ArthurDelbeke** [comment]
Yes of course. 

I'm not sure if the problem is with the select, but does the ScrollView have the `keyboardShouldPersistTaps` props?
I think my concern comes from the fact that the input above blur when I click on an element of the select, in this case it is my code that is problematic.

![RPReplay_Final1593087557](https://user-images.githubusercontent.com/34245352/85718900-40debe80-b6ef-11ea-8b84-feca2f4f0374.gif)

**Comment by artyorsh** [comment]
@ArthurDelbeke hm. Won't you dismiss the keyboard _before_ select is opened?

**Comment by artyorsh** [comment]
Select does nothing with Keyboard, since it doesn't require it. I guess the trick here is to handle gesture in some other places in code. It's weird enough the keyboard still shown when you expand select options.

**Comment by ArthurDelbeke** [comment]
Good idea, but when the keyboard goes, the elements of the select are already present and do not go down like the rest of the content.

But thanks for your help, I'm going to look for that side :)

![IMG_1646](https://user-images.githubusercontent.com/34245352/85720400-b008e280-b6f0-11ea-8b2f-abb032d7169d.PNG)

**Comment by t4ngth00** [comment]
@ArthurDelbeke I got the exact issue as your description and screenshots.

**Comment by anthowm** [comment]
@ArthurDelbeke @artyorsh A bit of topic, I see that you use select inner a modal. You are using kitten modal or another package ? because I'm trying with https://github.com/react-native-community/react-native-modal and the select is not working correctly it show the options behind the modal (after close the modal I can see it displayed). Any idea ?

**Comment by ArthurDelbeke** [comment]
> @ArthurDelbeke @artyorsh A bit of topic, I see that you use select inner a modal. You are using kitten modal or another package ? because I'm trying with https://github.com/react-native-community/react-native-modal and the select is not working correctly it show the options behind the modal (after close the modal I can see it displayed). Any idea ?

Hi, 
No sorry, I've build my own bottom-sheet : https://github.com/ArthurDelbeke/react-native-bottom-sheet

**Comment by kimwandev** [comment]
Hey guys, (maybe off-topic, but issue is caused by modal, keyboard and select control) anyone have experience form values getting cleared when rapidly clicking "Select" component when the keyboard is open?
