### ISSUE TITLE
Radio should have property value

### ISSUE THREAD

**Issue by violabg** [akveo/react-native-ui-kitten#1190]
# 🚀 Feature Proposal

It would be very useful to have **value** property on Radio components and RadioGroup with **defaultValue** and **value** to select the correct Radio.

## Motivation

most of the time you need to associate data to RadioGroup and just the index value is not enough.

**Comment by artyorsh** [comment]
I would discard this because we can say the same about each component that could be associated with forms.
We try to keep this package bare so that it's only able to render a component, assuming the rest work should be done by user because the business logic is always different.

I already have a set of components that are easy to bind with Formik, including RadioGroup. We'll probably introduce that as plugin in future.
