### ISSUE TITLE
Inconsistent Form component styles (Input, Select, DatePicker, AutoComplete)

### ISSUE THREAD

**Issue by akgunfu** [akveo/react-native-ui-kitten#1217]
## 🐛 Bug Report
Hi,
Mentioned components in title when used together looks different than expected. Container vertical margins, placeholder horizontal margins with and without accessories are different for these components. I am not sure if this is intentional in design system but in these state to use these components extra steps like styling to match with other components seems to be necessary on developer side.

Examples:
1 - **Input and autocomplete components both have default vertical margin, but select and datepicker do not.**
    This can be handled by wrapping select and datepicker components with margin. Then wrapper should always match the same margin with input and autocomplete. (Wrapper then should handle custom mapping, dynamic screens etc.)

2 - **Placeholders do not horizontally align for different components with same width.**
   Example, if input placeholder is 5px from left, select placeholder is 3px from left, then the datepicker is completely different (5px and 3px are examples)
   To handle this, I used placeholder function and wrapped placeholders with same margin. But **Input does not have placeholder function.** So most components look aligned, but there are still differences. 
Select, Datepicker => `placeholder?: RenderProp<TextProps> | React.ReactText;`, Input => `placeholder?: React.ReactText;`
<img width="378" alt="Screen Shot 2020-08-13 at 00 04 36" src="https://user-images.githubusercontent.com/11071496/90067981-964f4900-dcf8-11ea-9320-b7f2710b7d2e.png">

3 - **Datepicker placeholder with and without accessory has different alignments**
   With no accessories, datepicker placeholder is aligned to left but with left accessory it is aligned to right. Custom styling in placeholder function do not help it to be aligned to left. 
<img width="378" alt="Screen Shot 2020-08-13 at 00 06 13" src="https://user-images.githubusercontent.com/11071496/90068131-d1517c80-dcf8-11ea-8b72-c6162a2719bb.png">
<img width="377" alt="Screen Shot 2020-08-13 at 00 08 53" src="https://user-images.githubusercontent.com/11071496/90068351-2e4d3280-dcf9-11ea-908b-259dace5a1f3.png">
<img width="376" alt="Screen Shot 2020-08-13 at 00 09 17" src="https://user-images.githubusercontent.com/11071496/90068391-3c02b800-dcf9-11ea-9638-235bbf471bfa.png">

## To Reproduce

Below sample with no extra global styling

`const renderIcon = (name: string) => {
  return (props: any) => <Icon {...props} name={name} />;
};`

      ```
     <ScrollView style={{ flex: 1 }}>
      <Layout style={{ padding: 20 }}>
        <Text
          category={'h5'}
          style={{ textAlign: 'center', marginVertical: 20 }}>
          bare usage with placeholders
        </Text>

        <Input placeholder="Input" />
        <Select placeholder="Select" />
        <Datepicker placeholder="Datepicker" />
        <Autocomplete placeholder="Autocomplete" />

        <Divider style={{ marginVertical: 20 }} />
        <Text
          category={'h5'}
          style={{ textAlign: 'center', marginVertical: 20 }}>
          with left Accessory
        </Text>

        <Input accessoryLeft={renderIcon('star')} placeholder="Input" />
        <Select accessoryLeft={renderIcon('star')} placeholder="Select" />
        <Datepicker
          accessoryLeft={renderIcon('star')}
          placeholder={'Datepicker'}
        />
        <Autocomplete
          accessoryLeft={renderIcon('star')}
          placeholder="Autocomplete"
        />

        <Divider style={{ marginVertical: 20 }} />
        <Text
          category={'h5'}
          style={{ textAlign: 'center', marginVertical: 20 }}>
          with right Accessory
        </Text>

        <Input accessoryRight={renderIcon('star')} placeholder="Input" />
        <Select accessoryRight={renderIcon('star')} placeholder="Select" />
        <Datepicker
          accessoryRight={renderIcon('star')}
          placeholder={'Datepicker'}
        />
        <Autocomplete
          accessoryRight={renderIcon('star')}
          placeholder="Autocomplete"
        />

        <Divider style={{ marginVertical: 20 }} />
        <Text
          category={'h5'}
          style={{ textAlign: 'center', marginVertical: 20 }}>
          with both accessories
        </Text>

        <Input
          accessoryLeft={renderIcon('star')}
          accessoryRight={renderIcon('star')}
          placeholder="Input"
        />
        <Select
          accessoryLeft={renderIcon('star')}
          accessoryRight={renderIcon('star')}
          placeholder="Select"
        />
        <Datepicker
          accessoryLeft={renderIcon('star')}
          accessoryRight={renderIcon('star')}
          placeholder={'Datepicker'}
        />
        <Autocomplete
          accessoryLeft={renderIcon('star')}
          accessoryRight={renderIcon('star')}
          placeholder="Autocomplete"
        />
      </Layout>
    </ScrollView>
     ```

## Expected behavior

Form components should feel naturally aligned

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0     |
| @ui-kitten/components   |    5.0.0     |

## Environment information

```bash
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.7.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 26, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1
      System Images: android-16 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.0.1 4.0.1
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1

```

**Comment by Codelica** [comment]
RangeDatepicker is also inconsistent, behaving like DatePicker.   What are people doing to normalize for now? Some items don't seem to be tweakable via style overrides or mapping, unless I'm missing something.

**Comment by lyqht** [comment]
still facing the same issue now

<img width="386" alt="image" src="https://user-images.githubusercontent.com/35736525/161117246-87dc4ade-606b-46f1-bcc9-0374b1213c02.png">

**Comment by elavneet** [comment]
I used this to center the content.

```javascript
 controlStyle={{
    justifyContent: 'center',
}}
```

**Comment by bataevvlad** [comment]
Dear @akgunfu,

Thank you for reaching out and providing feedback on the UI components. We understand your concerns regarding the differences in styling and alignment between the components. We would like to assure you that our components are designed to be flexible and customizable, allowing developers to modify them according to their specific needs.

Regarding your specific points:

- Vertical margins: Wrapping the select and datepicker components with a margin container to match the vertical margin of the input and autocomplete components is a valid approach. This way, you can achieve consistent vertical spacing across all components.

- Placeholder alignment: We acknowledge that there might be variations in the horizontal alignment of placeholders across different components. You can use the placeholder function and apply custom styling to achieve consistent alignment. We apologize for the inconvenience caused by the absence of a placeholder function in the Input component. You can consider using alternative techniques like setting the initial value as a placeholder or applying additional styling to align the placeholder.

- Datepicker placeholder alignment with and without accessories: We understand that the alignment of the datepicker placeholder might differ based on the presence of accessories. Custom styling in the placeholder function might not resolve this issue entirely. You can explore different styling approaches, such as adjusting padding or margins, to achieve the desired alignment for both scenarios.

We appreciate your feedback and will take it into consideration for future improvements. If you have any further questions or need assistance with customization, please feel free to reach out to our support team.

Best regards,
Vladislav

**Comment by Codelica** [comment]
I'm confused.  This was closed because there is sufficient flexibility to manually modify component styling so they are uniform?   Don't get me wrong, I really appreciate what UI Kitten provides, but one of the biggest benefits of using a UI library is look-and-feel consistency out of the box.
