### ISSUE TITLE
UI Kitten Select Exception

### ISSUE THREAD

**Issue by justmv** [akveo/react-native-ui-kitten#1239]
I basically copy/pasted the example from the documentation

```
<Select
 selectedIndex={this.currLangIndex}
  onSelect={(index) => {
  this.currLangIndex = index;
}}>
  <SelectItem title="Option1" />
  <SelectItem title="Option2" />
</Select>
```
and I get the following error:
```
TypeError: undefined is not an object (evaluating 'props.getItem')
 This error is located at:
    in FlatList (created by List)
    in List (created by Context.Consumer)
    in Wrapper (created by List)
    in List (created by Autocomplete)
    in RCTView (at View.js:34)
    in View (created by PopoverView)
    in RCTView (at View.js:34)
    in View (created by PopoverView)
    in PopoverView (created by Context.Consumer)
    in Wrapper (created by PopoverView)
    in PopoverView
    in Unknown
    in RCTView (at View.js:34)
    in View (created by ModalResolver)
    in ModalResolver (created by ModalPanel)
    in RCTView (at View.js:34)
    in View (created by ModalPanel)
    in ModalPanel (created by ApplicationProvider)
    in ThemeProvider (created by StyleProvider)
    in MappingProvider (created by StyleProvider)
    in StyleProvider (created by ApplicationProvider)
    in ApplicationProvider (at app.tsx:65)
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
```

Any ideas why this is happening?

**Comment by kris-dci** [comment]
try removing "@babel/plugin-proposal-class-properties.. read about it several times ... Maybe it solves the problem...Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: kwml <notifications@github.com> Datum: 10.09.20  22:15  (GMT+01:00) An: akveo/react-native-ui-kitten <react-native-ui-kitten@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: [akveo/react-native-ui-kitten] UI Kitten Select Exception (#1239) 
I basically copy/pasted the example from the documentation
<Select
 selectedIndex={this.currLangIndex}
  onSelect={(index) => {
  this.currLangIndex = index;
}}>
  <SelectItem title="Option1" />
  <SelectItem title="Option2" />
</Select>

and I get the following error:
TypeError: undefined is not an object (evaluating 'props.getItem')
 This error is located at:
    in FlatList (created by List)
    in List (created by Context.Consumer)
    in Wrapper (created by List)
    in List (created by Autocomplete)
    in RCTView (at View.js:34)
    in View (created by PopoverView)
    in RCTView (at View.js:34)
    in View (created by PopoverView)
    in PopoverView (created by Context.Consumer)
    in Wrapper (created by PopoverView)
    in PopoverView
    in Unknown
    in RCTView (at View.js:34)
    in View (created by ModalResolver)
    in ModalResolver (created by ModalPanel)
    in RCTView (at View.js:34)
    in View (created by ModalPanel)
    in ModalPanel (created by ApplicationProvider)
    in ThemeProvider (created by StyleProvider)
    in MappingProvider (created by StyleProvider)
    in StyleProvider (created by ApplicationProvider)
    in ApplicationProvider (at app.tsx:65)
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)

Any ideas why this is happening?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/akveo/react-native-ui-kitten/issues/1239",
"url": "https://github.com/akveo/react-native-ui-kitten/issues/1239",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by kwml** [comment]
> babel/plugin-proposal-class-properties

It did not fix the issue

**Comment by artyorsh** [comment]
I can confirm that currently there are some issues connected to the `@babel/plugin-proposal-class-properties` package.

> Did not fix the issue

Make sure to clean Metro Bundler cache.
