### ISSUE TITLE
Future plans?

### ISSUE THREAD

**Issue by Frans-L** [akveo/react-native-ui-kitten#1273]
## 💬 Question

Hey! I really love this library. Really polished and well documented 💯 

However, I'm wondering what the future plans of the UI-Kitten. It seems like there haven't been any updates since May 2020.

Is this library still being maintained and developed further? 😄

**Comment by Bandwagoner** [comment]
Also interested in knowing this considering I started a new project with this library. It's been great aside from a few small bugs.

**Comment by artyorsh** [comment]
Hi everyone 👋  We postponed the maintenance of the library and related products (Eva, Kitten Tricks) since we had to focus on other products which actually bring money to support our Open Source. That was for the COVID-19 reasons. We'll definitely get back when the things become better with huge amount of fresh ideas, packages to extend the library and many more :)

Currently I spend my personal time to support several open issues, but I'm not responsible to merge PR's, add Bug Fixes without other teammates review and approval.

Sorry for not putting this info for a such long period and thanks for your interest. Stay tuned :)

**Comment by artyorsh** [comment]
@Bandwagoner if you have a project where you would like to use the library but a few issues is a blocker, I would suggest starting with a fork of the project, where you can close them. If you have questions regarding this, please [open an issue](https://github.com/akveo/react-native-ui-kitten/issues/new/choose) so I can help with that. Thanks for your understanding.

**Comment by robertwt7** [comment]
The library is really good compared to the other ui kit out there! Hopefully you guys can get back on your feet post covid :), all the best.

I'll keep using the library in the meanwhile

**Comment by anthowm** [comment]
@artyorsh There is the possibility to activate github sponsor and openCollective to try to speed up the return to the repository (like chakraUI). I think that like me other developers can help the project in this way.

**Comment by murbanowicz** [comment]
@artyorsh Would you try to discuss with your teammates even one-off session of merging PRs and releasing one new version? Is it possible at all?

**Comment by vitorverasm** [comment]
We ❤️ this UI library, I've used a lot and it surprised me how well documented and consistent this components are. We understand that for now(for COVID-19 purposes) the maintenance of this project is a little slow. But there's something that we can try to reach like:
* Make a 2021 roadmap
* Review open PR's an put them into milestones
* Open sponsor options for this project

**Comment by kuasha420** [comment]
I'm also a long time user and would love to help in any way possible.
