### ISSUE TITLE
Documentation parser is incompatible

### ISSUE THREAD

**Issue by artyorsh** [akveo/react-native-ui-kitten#131]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Doc-prsr or some doc-level dependency behavior is changed and incompatible. See screenshot below:
![image](https://user-images.githubusercontent.com/10753921/42759430-a2638dbc-890f-11e8-842a-5ccd288c3557.png)

**Expected behavior:**
Generated documentations should be like this:
![image](https://user-images.githubusercontent.com/10753921/42759485-d423f742-890f-11e8-985e-d280a320b8e2.png)

**Steps to reproduce:**
Check out to react-native-ui-kitten release version and current version from master branch to ensure.

**Comment by nnixaa** [comment]
@artyorsh @malashkevich as we updated the doc-prsr with some new features which introduced a couple of breaking changes, I would suggest keeping Kitten docs locked on 2.0.2 version of the parser (https://github.com/akveo/doc-prsr/blob/master/CHANGELOG.md#202-2018-02-06).
Then, we block this issue until the New Kitten (4.x?) so that during that major update we also update the documentation website and hence the parser.

**Comment by artyorsh** [comment]
Closing due to fix in doc-prsr v2.0.3
