### ISSUE TITLE
How do I add a new component to the mapping?

### ISSUE THREAD

**Issue by petruspierre** [akveo/react-native-ui-kitten#1361]
## 💬 Question

I am creating a component for the library, it is already working, however, when I went to add the styles using the `styled` function I received the following error:

"Pagination: unsupported configuration. Using UI Kitten components is only possible with configuring ApplicationProvider. [...] In the case you have all in place, there might be an incorrect usage of a 'styled' function."

I'm using Kitten Tricks to test the component I'm creating and running with `yarn demo start:dev`

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |    5.0.0     |

**Comment by artyorsh** [comment]
👋 
Here is a [guide](https://akveo.github.io/react-native-ui-kitten/docs/design-system/custom-component-mapping#prepare-the-boilerplate)

**Comment by petruspierre** [comment]
Actually this is not for my case, I am creating a component for the library (help to solve an issue), and not for a project of mine

**Comment by artyorsh** [comment]
If you're building for the library, it assumes that the library user should run it as a plugin above UI Kitten components. Your library user will still have to wrap the root component in ApplicationProvider so that the component can be given processed stylings, what actually ApplicationProvider does.
