### ISSUE TITLE
Performance issue - App is loading 4-5 seconds late

### ISSUE THREAD

**Issue by scrapecoder** [akveo/react-native-ui-kitten#1374]
## 🐛 Bug Report

 When the app is starting its showing white screen for 4-5 seconds than redirected me to the screen. i followed the [https://akveo.github.io/react-native-ui-kitten/docs/guides/improving-performance#improving-performance](url) but still nothing changed. i'm not doing any custom `mapping`.

## Link to runnable example or repository (highly encouraged)
`App.js`

`<ApplicationProvider {...eva} theme={evaTheme}>
					<NavigationContainer>
						{state.userToken == null ? (
							<RootStackScreen skipIntro={state.skipIntro} />
						) : (
							<DrawerNavigator name={state.userName} />
						)}
					</NavigationContainer>
				</ApplicationProvider>`

`metro.config.js`

   `const MetroConfig = require('@ui-kitten/metro-config')`
`const evaConfig = {
	evaPackage : '@eva-design/eva'
}`
`module.exports = MetroConfig.create(evaConfig, {
	transformer : {
		getTransformOptions : async () => ({
			transform : {
				experimentalImportSupport : false,
				inlineRequires            : false
			}
		})
	}
})`

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0     |
| @ui-kitten/components   |    5.0.0     |

**Comment by effektsvk** [comment]
Hello, I'm having the same issue. What I found out was that when the app starts, inside `ApplicationProvider` there is a code that processes the whole JSON file which contains the mapping. This file has over 5k lines and is loaded and processed on every app launch.

I used a workaround for this. Inside the `ApplicationProvider`, I logged the whole object containing all the styles that were generated (see line 14 in patch below), then I saved it into a JSON file and passed it as a prop into ApplicationProvider (I created a new prop).

**NOTE**: This patch is for `react-native-ui-kitten@4.4.1`. I will be upgrading to version 5 in the upcoming days, maybe that will solve the issue, but since you are already on v5 and you're having issues, I think this will help you too (I didn't inspect v5 code yet).

Patch:
```diff
--- node_modules/react-native-ui-kitten/theme/application/applicationProvider.component.js
+++ node_modules/react-native-ui-kitten/theme/application/applicationProvider.component.js
@@ -65,13 +65,14 @@ class ApplicationProvider extends react_1.default.Component {
             const customizedMapping = lodash_merge_1.default({}, mapping, custom);
             return this.schemaProcessor.process(customizedMapping);
         };
-        if (!this.state.styles) {
-            const { mapping, customMapping } = this.props;
-            this.state.styles = this.createStyles(mapping, customMapping);
-        }
+        // if (!this.state.styles) {
+        //     const { mapping, customMapping } = this.props;
+        //     this.state.styles = this.createStyles(mapping, customMapping);
+        //     console.log(JSON.stringify(this.createStyles(mapping, customMapping)))
+        // }
     }
     render() {
-        return (react_1.default.createElement(styleProvider_component_1.StyleProvider, { theme: this.props.theme, styles: this.state.styles },
+        return (react_1.default.createElement(styleProvider_component_1.StyleProvider, { theme: this.props.theme, styles: this.props.styles },
             react_1.default.createElement(modalPanel_component_1.ModalPanel, null, this.props.children)));
     }
 }
```

**Comment by LadislavBohm** [comment]
I had the same issue but only on Android. For me when I disabled Hermes, made clean and rebuild of the app it starts much faster. There is like 0.5 second delay which is acceptable for me.

**Comment by artyorsh** [comment]
Thank you @sschottler for making it clear. I think we may close this issue. Please refer to the #1057 for the details
