### ISSUE TITLE
dropdown in landscape mode has extra space and is not displayed correctly

### ISSUE THREAD

**Issue by soheilaGhayour** [akveo/react-native-ui-kitten#1394]
## 🐛 Bug Report

Trying components which have a drop down list (such as Select or Autocomplete) in landscape mode results in the list having extra space, which I assume is caused because of the mobile notch.
In portrait mode dropdowns are shown just fine.
![issue](https://user-images.githubusercontent.com/66425323/113449539-4eaa3880-9413-11eb-90c4-3c4ecd878437.jpg)

## To Reproduce

```
const SelectComponent = () => {
  const [selectedIndex, setSelectedIndex] = React.useState(new IndexPath(0));
  return (
    <Layout style={{minHeight:10,width:200}} level='1'>
      <Select
        selectedIndex={selectedIndex}
        onSelect={index => setSelectedIndex(index)}>
        <SelectItem title='Option 1'/>
        <SelectItem title='Option 2'/>
        <SelectItem title='Option 3'/>
      </Select>
    </Layout>
  );
};

export default SelectComponent ;
```
## Expected behavior
Dropdowns being shown correctly in any mode
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |  2.0.0      |
| @ui-kitten/components   |   5.0.0      |

Thanks in advance

**Comment by whitestranger7** [comment]
Hi, @soheilaGhayour. Thanks for noticing the issue. The issue seems to be appeared because of your `StatusBar` configuration on Android. Specifically for Android, we've `ModalService` that could apply your current Status Bar height into all modal-based components like: `Select`, `Popover`, `Modal`, ect.

Please, paste this code into your application in order to enable Status Bar height support:

```js
...
import { ModalService } from '@ui-kitten/components'

ModalService.setShouldUseTopInsets = true
...
```
