### ISSUE TITLE
Drawer Injects items to DrawerItems ?

### ISSUE THREAD

**Issue by PupoSDC** [akveo/react-native-ui-kitten#1395]
## 💬 Question

When profiling my application I realised that my navigation `DrawerItem`s where taking some 200ms to render, and due to application design, they need to be rendered quite frequently. So I decided to memoize them, but it just wouldn't work.

the reason appears to be a mysterious "descriptor" prop being passed to all my `DrawerNavigator` container. Here is some code

```tsx
export const TestNavigationDrawer: React.FunctionComponent<TestNavigationDrawerProps> = ({
  navigation: { navigate },
  state: { routes },
}) => {
  // some code to get props from state

  return (
    <Drawer selectedIndex={new IndexPath(currentIndex)}>
      {questions.map((question) => (
        <QuestionDrawerItem
          correct={question.correct}
          selected={question.selected}
          index={question.index}
          key={question.id}
          navigate={navigate}
          finished={finished}
        />
      ))}
    </Drawer>
  );
};

const QuestionDrawerItem = React.memo<QuestionDrawerItemProps>(
  ({ correct, selected, finished, index, navigate }) => (
    <DrawerItem
      accessoryLeft={(props) => (
        <QuestionStateIcon
          {...props}
          finished={finished}
          selected={selected}
          correct={correct}
        />
      )}
      title={`Question ${index + 1}`}
      onPress={() => navigate("Question", { questionIndex: index })}
    />
  ),
  (prevProps, oldProps) => {
    if (prevProps.index === 0) {
      console.log(`\n\nEntry number ${prevProps.index}`);
      Object.keys(prevProps).map(key => {
        console.log(key, prevProps[key] === oldProps[key]);
      })
    }
    return false;
  }
);
```

with this i can see

```
Entry number 0
correct true
selected true
index true
navigate true
finished true
descriptor false
onPress true
children true
```

`descriptor` changes with every render, invalidating the `memoization`. The contents of this prop are:

```
Object {
  "groupIndices": undefined,
  "index": IndexPath {
    "equals": [Function anonymous],
    "row": 0,
    "section": undefined,
  },
}
```

For now i fixed the issue with this memoization props checking function:

```ts
  (prevProps, oldProps) => 
      (prevProps.correct === oldProps.correct) &&
      (prevProps.selected === oldProps.selected) &&
      (prevProps.finished === oldProps.finished) &&
      (prevProps.index === oldProps.index) &&
      (prevProps.navigate === oldProps.navigate),
```     

So, down to my questions:

- Why is this prop passed down to `Drawer` children?
  - Is it safe to ignore in the memoization?
  - Is this behaviour documented somewhere and i missed it?  

Thank you all for your work in this project!

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |  2.0.0      |
| @ui-kitten/components   |  5.0.0      |

**Comment by PupoSDC** [comment]
Didn't took me long to realize that yes, it has some problems. The automatic highlighting of the current selected item is gone.

I ended slightly modifying the code to this:

```tsx
type QuestionDrawerItemProps = {
  correct: string;
  questionSelected?: string;
  finished: boolean;
  index: number;
  navigate: TestNavigationDrawerProps["navigation"]["navigate"];
} & MenuItemProps;

const QuestionDrawerItem = React.memo<QuestionDrawerItemProps>(
  ({ correct, questionSelected, finished, index, navigate, ...menuItemProps }) => (
    <DrawerItem
      {...menuItemProps}
      accessoryLeft={(props) => (
        <QuestionStateIcon
          {...props}
          finished={finished}
          selected={questionSelected}
          correct={correct}
        />
      )}
      title={`Question ${index + 1}`}
      onPress={() => navigate("Question", { questionIndex: index })}
    />
  ),
  (prevProps, nextProps) =>
    prevProps.questionSelected === nextProps.questionSelected &&
    prevProps.correct === nextProps.correct &&
    prevProps.selected === nextProps.selected &&
    prevProps.finished === nextProps.finished &&
    prevProps.index === nextProps.index &&
    prevProps.navigate === nextProps.navigate
);
```

I don't see a way around this memoization, and i question if it would be possible to have it directly in the `MenuItem` component. 

And to answer my other question, yes this behaviour is document in code. The children of `Drawer` should be of type `ChildrenWithProps<MenuItemProps>`.

I hope this monologue helps someone else in the future.

**Comment by north8side** [comment]
The code of conduct was taken out and the private policy needs to be add the I'd is link master in stead of master change to find the separate trans. Of the writing as well the issue

Powered by Cricket Wireless
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: PupoSDC ***@***.***>
Sent: Monday, April 5, 2021 1:47:27 PM
To: akveo/react-native-ui-kitten ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [akveo/react-native-ui-kitten] Drawer Injects items to DrawerItems ? (#1395)


💬 Question

When profiling my application I realised that my navigation DrawerItems where taking some 200ms to render, and due to application design, they need to be rendered quite frequently. So I decided to memoize them, but it just wouldn't work.

the reason appears to be a mysterious "descriptor" prop being passed to all my DrawerNavigator container. Here is some code

export const TestNavigationDrawer: React.FunctionComponent<TestNavigationDrawerProps> = ({

  navigation: { navigate },

  state: { routes },

}) => {

  // some code to get props from state



  return (

    <Drawer selectedIndex={new IndexPath(currentIndex)}>

      {questions.map((question) => (

        <QuestionDrawerItem

          correct={question.correct}

          selected={question.selected}

          index={question.index}

          key={question.id}

          navigate={navigate}

          finished={finished}

        />

      ))}

    </Drawer>

  );

};



const QuestionDrawerItem = React.memo<QuestionDrawerItemProps>(

  ({ correct, selected, finished, index, navigate }) => (

    <DrawerItem

      accessoryLeft={(props) => (

        <QuestionStateIcon

          {...props}

          finished={finished}

          selected={selected}

          correct={correct}

        />

      )}

      title={`Question ${index + 1}`}

      onPress={() => navigate("Question", { questionIndex: index })}

    />

  ),

  (prevProps, oldProps) => {

    if (prevProps.index === 0) {

      console.log(`\n\nEntry number ${prevProps.index}`);

      Object.keys(prevProps).map(key => {

        console.log(key, prevProps[key] === oldProps[key]);

      })

    }

    return false;

  }

);

with this i can see

Entry number 0

correct true

selected true

index true

navigate true

finished true

descriptor false

onPress true

children true



descriptor changes with every render, invalidating the memoization. The contents of this prop are:

Object {

  "groupIndices": undefined,

  "index": IndexPath {

    "equals": [Function anonymous],

    "row": 0,

    "section": undefined,

  },

}



For now i fixed the issue with this memoization props checking function:

  (prevProps, oldProps) =>

      (prevProps.correct === oldProps.correct) &&

      (prevProps.selected === oldProps.selected) &&

      (prevProps.finished === oldProps.finished) &&

      (prevProps.index === oldProps.index) &&

      (prevProps.navigate === oldProps.navigate),

So, down to my questions:

  *   Why is this prop passed down to Drawer children?
     *   Is it safe to ignore in the memoization?
     *   Is this behaviour documented somewhere and i missed it?

Thank you all for your work in this project!

UI Kitten and Eva version
Package Version
@eva-design/eva 2.0.0
@ui-kitten/components   5.0.0

**Comment by north8side** [comment]
Found in luling tx area taken from houston tx from kitten prior to the absence.of her presents.

Powered by Cricket Wireless
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: PupoSDC ***@***.***>
Sent: Monday, April 5, 2021 1:47:27 PM
To: akveo/react-native-ui-kitten ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [akveo/react-native-ui-kitten] Drawer Injects items to DrawerItems ? (#1395)


💬 Question

When profiling my application I realised that my navigation DrawerItems where taking some 200ms to render, and due to application design, they need to be rendered quite frequently. So I decided to memoize them, but it just wouldn't work.

the reason appears to be a mysterious "descriptor" prop being passed to all my DrawerNavigator container. Here is some code

export const TestNavigationDrawer: React.FunctionComponent<TestNavigationDrawerProps> = ({

  navigation: { navigate },

  state: { routes },

}) => {

  // some code to get props from state



  return (

    <Drawer selectedIndex={new IndexPath(currentIndex)}>

      {questions.map((question) => (

        <QuestionDrawerItem

          correct={question.correct}

          selected={question.selected}

          index={question.index}

          key={question.id}

          navigate={navigate}

          finished={finished}

        />

      ))}

    </Drawer>

  );

};



const QuestionDrawerItem = React.memo<QuestionDrawerItemProps>(

  ({ correct, selected, finished, index, navigate }) => (

    <DrawerItem

      accessoryLeft={(props) => (

        <QuestionStateIcon

          {...props}

          finished={finished}

          selected={selected}

          correct={correct}

        />

      )}

      title={`Question ${index + 1}`}

      onPress={() => navigate("Question", { questionIndex: index })}

    />

  ),

  (prevProps, oldProps) => {

    if (prevProps.index === 0) {

      console.log(`\n\nEntry number ${prevProps.index}`);

      Object.keys(prevProps).map(key => {

        console.log(key, prevProps[key] === oldProps[key]);

      })

    }

    return false;

  }

);

with this i can see

Entry number 0

correct true

selected true

index true

navigate true

finished true

descriptor false

onPress true

children true



descriptor changes with every render, invalidating the memoization. The contents of this prop are:

Object {

  "groupIndices": undefined,

  "index": IndexPath {

    "equals": [Function anonymous],

    "row": 0,

    "section": undefined,

  },

}



For now i fixed the issue with this memoization props checking function:

  (prevProps, oldProps) =>

      (prevProps.correct === oldProps.correct) &&

      (prevProps.selected === oldProps.selected) &&

      (prevProps.finished === oldProps.finished) &&

      (prevProps.index === oldProps.index) &&

      (prevProps.navigate === oldProps.navigate),

So, down to my questions:

  *   Why is this prop passed down to Drawer children?
     *   Is it safe to ignore in the memoization?
     *   Is this behaviour documented somewhere and i missed it?

Thank you all for your work in this project!

UI Kitten and Eva version
Package Version
@eva-design/eva 2.0.0
@ui-kitten/components   5.0.0

**Comment by north8side** [comment]
Yes I found this in my files as well as someone else applying to them. It was to his or they were taking something. I opened it to find out who it is.

Powered by Cricket Wireless
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: PupoSDC ***@***.***>
Sent: Monday, April 5, 2021 1:47:27 PM
To: akveo/react-native-ui-kitten ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [akveo/react-native-ui-kitten] Drawer Injects items to DrawerItems ? (#1395)


💬 Question

When profiling my application I realised that my navigation DrawerItems where taking some 200ms to render, and due to application design, they need to be rendered quite frequently. So I decided to memoize them, but it just wouldn't work.

the reason appears to be a mysterious "descriptor" prop being passed to all my DrawerNavigator container. Here is some code

export const TestNavigationDrawer: React.FunctionComponent<TestNavigationDrawerProps> = ({

  navigation: { navigate },

  state: { routes },

}) => {

  // some code to get props from state



  return (

    <Drawer selectedIndex={new IndexPath(currentIndex)}>

      {questions.map((question) => (

        <QuestionDrawerItem

          correct={question.correct}

          selected={question.selected}

          index={question.index}

          key={question.id}

          navigate={navigate}

          finished={finished}

        />

      ))}

    </Drawer>

  );

};



const QuestionDrawerItem = React.memo<QuestionDrawerItemProps>(

  ({ correct, selected, finished, index, navigate }) => (

    <DrawerItem

      accessoryLeft={(props) => (

        <QuestionStateIcon

          {...props}

          finished={finished}

          selected={selected}

          correct={correct}

        />

      )}

      title={`Question ${index + 1}`}

      onPress={() => navigate("Question", { questionIndex: index })}

    />

  ),

  (prevProps, oldProps) => {

    if (prevProps.index === 0) {

      console.log(`\n\nEntry number ${prevProps.index}`);

      Object.keys(prevProps).map(key => {

        console.log(key, prevProps[key] === oldProps[key]);

      })

    }

    return false;

  }

);

with this i can see

Entry number 0

correct true

selected true

index true

navigate true

finished true

descriptor false

onPress true

children true



descriptor changes with every render, invalidating the memoization. The contents of this prop are:

Object {

  "groupIndices": undefined,

  "index": IndexPath {

    "equals": [Function anonymous],

    "row": 0,

    "section": undefined,

  },

}



For now i fixed the issue with this memoization props checking function:

  (prevProps, oldProps) =>

      (prevProps.correct === oldProps.correct) &&

      (prevProps.selected === oldProps.selected) &&

      (prevProps.finished === oldProps.finished) &&

      (prevProps.index === oldProps.index) &&

      (prevProps.navigate === oldProps.navigate),

So, down to my questions:

  *   Why is this prop passed down to Drawer children?
     *   Is it safe to ignore in the memoization?
     *   Is this behaviour documented somewhere and i missed it?

Thank you all for your work in this project!

UI Kitten and Eva version
Package Version
@eva-design/eva 2.0.0
@ui-kitten/components   5.0.0

**Comment by north8side** [comment]
I also have people going in my files but there was one years ago that has came back to my files.

Powered by Cricket Wireless
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: PupoSDC ***@***.***>
Sent: Monday, April 5, 2021 1:47:27 PM
To: akveo/react-native-ui-kitten ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [akveo/react-native-ui-kitten] Drawer Injects items to DrawerItems ? (#1395)


💬 Question

When profiling my application I realised that my navigation DrawerItems where taking some 200ms to render, and due to application design, they need to be rendered quite frequently. So I decided to memoize them, but it just wouldn't work.

the reason appears to be a mysterious "descriptor" prop being passed to all my DrawerNavigator container. Here is some code

export const TestNavigationDrawer: React.FunctionComponent<TestNavigationDrawerProps> = ({

  navigation: { navigate },

  state: { routes },

}) => {

  // some code to get props from state



  return (

    <Drawer selectedIndex={new IndexPath(currentIndex)}>

      {questions.map((question) => (

        <QuestionDrawerItem

          correct={question.correct}

          selected={question.selected}

          index={question.index}

          key={question.id}

          navigate={navigate}

          finished={finished}

        />

      ))}

    </Drawer>

  );

};



const QuestionDrawerItem = React.memo<QuestionDrawerItemProps>(

  ({ correct, selected, finished, index, navigate }) => (

    <DrawerItem

      accessoryLeft={(props) => (

        <QuestionStateIcon

          {...props}

          finished={finished}

          selected={selected}

          correct={correct}

        />

      )}

      title={`Question ${index + 1}`}

      onPress={() => navigate("Question", { questionIndex: index })}

    />

  ),

  (prevProps, oldProps) => {

    if (prevProps.index === 0) {

      console.log(`\n\nEntry number ${prevProps.index}`);

      Object.keys(prevProps).map(key => {

        console.log(key, prevProps[key] === oldProps[key]);

      })

    }

    return false;

  }

);

with this i can see

Entry number 0

correct true

selected true

index true

navigate true

finished true

descriptor false

onPress true

children true



descriptor changes with every render, invalidating the memoization. The contents of this prop are:

Object {

  "groupIndices": undefined,

  "index": IndexPath {

    "equals": [Function anonymous],

    "row": 0,

    "section": undefined,

  },

}



For now i fixed the issue with this memoization props checking function:

  (prevProps, oldProps) =>

      (prevProps.correct === oldProps.correct) &&

      (prevProps.selected === oldProps.selected) &&

      (prevProps.finished === oldProps.finished) &&

      (prevProps.index === oldProps.index) &&

      (prevProps.navigate === oldProps.navigate),

So, down to my questions:

  *   Why is this prop passed down to Drawer children?
     *   Is it safe to ignore in the memoization?
     *   Is this behaviour documented somewhere and i missed it?

Thank you all for your work in this project!

UI Kitten and Eva version
Package Version
@eva-design/eva 2.0.0
@ui-kitten/components   5.0.0

**Comment by north8side** [comment]
They took my gmail before and now they have tried taking lynda.com subscription and my some of my files as well they are trying to use my stuff to learn off of and did not make a profile they use files against me that I had. While i still learn. This happened recently when I stayed my families house. In luling tx

Powered by Cricket Wireless
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: PupoSDC ***@***.***>
Sent: Monday, April 5, 2021 1:47:27 PM
To: akveo/react-native-ui-kitten ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [akveo/react-native-ui-kitten] Drawer Injects items to DrawerItems ? (#1395)


💬 Question

When profiling my application I realised that my navigation DrawerItems where taking some 200ms to render, and due to application design, they need to be rendered quite frequently. So I decided to memoize them, but it just wouldn't work.

the reason appears to be a mysterious "descriptor" prop being passed to all my DrawerNavigator container. Here is some code

export const TestNavigationDrawer: React.FunctionComponent<TestNavigationDrawerProps> = ({

  navigation: { navigate },

  state: { routes },

}) => {

  // some code to get props from state



  return (

    <Drawer selectedIndex={new IndexPath(currentIndex)}>

      {questions.map((question) => (

        <QuestionDrawerItem

          correct={question.correct}

          selected={question.selected}

          index={question.index}

          key={question.id}

          navigate={navigate}

          finished={finished}

        />

      ))}

    </Drawer>

  );

};



const QuestionDrawerItem = React.memo<QuestionDrawerItemProps>(

  ({ correct, selected, finished, index, navigate }) => (

    <DrawerItem

      accessoryLeft={(props) => (

        <QuestionStateIcon

          {...props}

          finished={finished}

          selected={selected}

          correct={correct}

        />

      )}

      title={`Question ${index + 1}`}

      onPress={() => navigate("Question", { questionIndex: index })}

    />

  ),

  (prevProps, oldProps) => {

    if (prevProps.index === 0) {

      console.log(`\n\nEntry number ${prevProps.index}`);

      Object.keys(prevProps).map(key => {

        console.log(key, prevProps[key] === oldProps[key]);

      })

    }

    return false;

  }

);

with this i can see

Entry number 0

correct true

selected true

index true

navigate true

finished true

descriptor false

onPress true

children true



descriptor changes with every render, invalidating the memoization. The contents of this prop are:

Object {

  "groupIndices": undefined,

  "index": IndexPath {

    "equals": [Function anonymous],

    "row": 0,

    "section": undefined,

  },

}



For now i fixed the issue with this memoization props checking function:

  (prevProps, oldProps) =>

      (prevProps.correct === oldProps.correct) &&

      (prevProps.selected === oldProps.selected) &&

      (prevProps.finished === oldProps.finished) &&

      (prevProps.index === oldProps.index) &&

      (prevProps.navigate === oldProps.navigate),

So, down to my questions:

  *   Why is this prop passed down to Drawer children?
     *   Is it safe to ignore in the memoization?
     *   Is this behaviour documented somewhere and i missed it?

Thank you all for your work in this project!

UI Kitten and Eva version
Package Version
@eva-design/eva 2.0.0
@ui-kitten/components   5.0.0
