### ISSUE TITLE
Click on icon warning error in console

### ISSUE THREAD

**Issue by sergeu90** [akveo/react-native-ui-kitten#1402]
Hello everyone. Great library. Thanks for it.

## 🐛 Bug Report

I get your code in the example. https://akveo.github.io/react-native-ui-kitten/docs/assets/playground-build/#/InputAccessories
And I have warning in the console.

1. index.js:1 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
2. Warning: Unknown event handler property `onStartShouldSetResponder`. It will be ignored.
3. Warning: Unknown event handler property `onResponderGrant`. It will be ignored.
4. Warning: Unknown event handler property `onResponderMove`. It will be ignored.
5. index.js:1 Warning: Unknown event handler property `onResponderRelease`. It will be ignored.
6. index.js:1 Warning: Unknown event handler property `onResponderTerminate`. It will be ignored.
7. index.js:1 Warning: Unknown event handler property `onResponderTerminationRequest`. It will be ignored.
8. index.js:1 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `Icon`.

## To Reproduce

Get code from example and open in the web.

## Expected behavior

I think warning error  to need don't show

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0     |
| @ui-kitten/components   |   5.0.0      |

## Environment information

```bash

```

**Comment by sergeu90** [comment]
```
 <Pressable onPress={handleToggleSecureEntry}>
        <Icon style={props.style} name={secureTextEntry ? 'eye-off' : 'eye'} />
 </Pressable>
```

use Pressable instead TouchableWithoutFeedback not showing error .

**Comment by north8side** [comment]
Ok the grant was the what i was wonder and its location ignore for now is ok better yhat to close.

Powered by Cricket Wireless
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: sergeu90 ***@***.***>
Sent: Saturday, April 10, 2021 7:30:01 AM
To: akveo/react-native-ui-kitten ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [akveo/react-native-ui-kitten] Click on icon warning error in console (#1402)


Hello everyone. Great library. Thanks for it.

🐛 Bug Report

I get your code in the example. https://akveo.github.io/react-native-ui-kitten/docs/assets/playground-build/#/InputAccessories<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fakveo.github.io%2Freact-native-ui-kitten%2Fdocs%2Fassets%2Fplayground-build%2F%23%2FInputAccessories&data=04%7C01%7C%7Cca627f62eb4d4721b16208d8fc1c5d25%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637536546032981343%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=g0oNVEf30XBuNKefOhjfGxnKglKWIljo%2FOTcyUNfaIw%3D&reserved=0>
And I have warning in the console.

  1.  index.js:1 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
  2.  Warning: Unknown event handler property onStartShouldSetResponder. It will be ignored.
  3.  Warning: Unknown event handler property onResponderGrant. It will be ignored.
  4.  Warning: Unknown event handler property onResponderMove. It will be ignored.
  5.  index.js:1 Warning: Unknown event handler property onResponderRelease. It will be ignored.
  6.  index.js:1 Warning: Unknown event handler property onResponderTerminate. It will be ignored.
  7.  index.js:1 Warning: Unknown event handler property onResponderTerminationRequest. It will be ignored.
  8.  index.js:1 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of Icon.

To Reproduce

Get code from example and open in the web.

Expected behavior

I think warning error to need don't show

Link to runnable example or repository (highly encouraged)
UI Kitten and Eva version
Package Version
@eva-design/eva 2.0.0
@ui-kitten/components   5.0.0
Environment information

**Comment by flexbox** [comment]
@sergeu90 

If your problem is solved can you please close the issue? 
It sparks joy for maintainers ✨
