### ISSUE TITLE
How to remove outline for Input component for web?

### ISSUE THREAD

**Issue by siarheipashkevich** [akveo/react-native-ui-kitten#1422]
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.1.0    |
| @ui-kitten/components   |     5.1.0    |

![Screenshot from 2021-05-05 12-30-24](https://user-images.githubusercontent.com/7753600/117121936-f5c91980-ad9d-11eb-9113-161ffe6610e0.png)
![Screenshot from 2021-05-05 14-39-32](https://user-images.githubusercontent.com/7753600/117135567-c7ecd080-adaf-11eb-8c3c-c253a4a041a8.png)

```
  <Input
    label="Input label"
    autoCapitalize="none"
    autoCompleteType="email"
    textContentType="emailAddress"
    keyboardType="email-address"
  />
```
Thanks.

**Comment by sschottler** [comment]
I noticed this too. It appears to be a bug in 5.1. When I use 5.0 (and 2.0 for @eva-design/eva), it works as expected in web.

**Comment by sschottler** [comment]
It looks like UI Kitten needs to set the `accessible` prop to `false` on `TouchableWithoutFeedback` [here](https://github.com/akveo/react-native-ui-kitten/blob/1403fdb993f2b6f3fb46fcddfddb185d5652883a/src/components/ui/input/input.component.tsx#L263-L265) so it won't get outlined when tabbing. When I manually modified `node_modules/@ui-kitten/components/ui/input/input.component.js` to set this prop, it worked as expected when tabbing. `react-native-web` will render a div with `data-focusable="true" tabindex="0"` by default for `TouchableWithoutFeedback`, but setting `accessible={false}` will result in a div without those attributes.

https://github.com/akveo/react-native-ui-kitten/blob/1403fdb993f2b6f3fb46fcddfddb185d5652883a/src/components/ui/input/input.component.tsx#L263-L265

**Comment by sschottler** [comment]
Here are two fixes for the issue in the meantime:

1. Downgrade to `@ui-kitten/components@5.0` (you will also need `@eva-design/eva@2.0` since its mapping structure works with 5.0)
2. Use [patch-package](https://www.npmjs.com/package/patch-package) to patch the `@ui-kitten/components` package in postinstall step. I used it to generate this patch:

`@ui-kitten+components+5.1.0.patch`:

```diff
diff --git a/node_modules/@ui-kitten/components/ui/input/input.component.js b/node_modules/@ui-kitten/components/ui/input/input.component.js
index 4f24771..52a4e89 100644
--- a/node_modules/@ui-kitten/components/ui/input/input.component.js
+++ b/node_modules/@ui-kitten/components/ui/input/input.component.js
@@ -173,7 +173,7 @@ let Input = class Input extends react_1.default.Component {
     render() {
         const { eva, textStyle, label, caption, accessoryLeft, accessoryRight, ...textInputProps } = this.props;
         const evaStyle = this.getComponentStyle(eva.style);
-        return (react_1.default.createElement(devsupport_1.TouchableWithoutFeedback, { style: evaStyle.container, onPress: this.focus },
+        return (react_1.default.createElement(devsupport_1.TouchableWithoutFeedback, { accessible: false, style: evaStyle.container, onPress: this.focus },
             react_1.default.createElement(devsupport_1.FalsyText, { style: [evaStyle.label, styles.label], component: label }),
             react_1.default.createElement(react_native_1.View, { style: [evaStyle.inputContainer, styles.inputContainer] },
                 react_1.default.createElement(devsupport_1.FalsyFC, { style: evaStyle.icon, component: accessoryLeft }),

```

**Comment by 1jerry** [comment]
Thanks for this!
I have noticed the tabindex problems too.  It is poor UX to have to hit TAB twice to move between fields.  This fix makes perfect sense, but unfortunately, it does not work for me!  I have the exact same version.  I tried the patch, then reinstalled and tried to manually edit the input.component.js file, re-ran yarn.  Still doesn't work!  I even removed node_modules and reinstalled from scratch, made the edit and restarted.  No love.

Any clue to why I cannot get it to work?  Must be a bundling or cache issue, but I cannot think of what it could be.

And since this little change *breaks* keyboard usability, I am surprised there is no patch release yet.

**Comment by sschottler** [comment]
Hmm...if by "re-ran yarn" you mean you literally just ran `yarn` then that could yarn install the package again and override your manual change to `input.component.js`. Double check you still see the `accessible: false` prop you have to manually add in `input.component.js` after you run the app. If not, then something in your build/app start script might be overriding your manual changes. 

You could also try to `empty cache and hard reload` to make sure something isn't being cached locally for expo bundle script. Open chrome devtools and then you can right click the "reload this page" icon and a submenu with "empty cache and hard reload" should appear.
 
Also, are you in a monorepo structure by any chance? Sub package folders can have their own `node_modules` folders if they reference different versions of any shared packages that are hoisted at monorepo node_modules root. If one package in the monorepo references a different version of UI Kitten, then you might not be editing the right `node_modules` path or you might need to edit multiple versions of UI kitten at different node_modules paths.

That's what I can think of off the top of my head. Good luck!

**Comment by 1jerry** [comment]
Thanks for the quick reply.  To be more clear:

   1. I created a patch file before reinstalling ui-kitten and/or all
   packages.  double check the patch was in place
   2. I started from a fresh repo and *manually* updated the file with
   "accessible: false"
   3. I tried hard-reload
   4. We are not using expo and we are using Parcel for bundling. ICIM
   5. Was working perfectly with UI-Kitten 5.0 & eva 2.0.
   6. Yes, I'm using a monorepo, and I am in the correct folder (for React
   web).  I've also tried editing the version of the package in the
*native* folder,
   but it did nothing, which is expected.
   7. I know it is accessing the correct *input.component.js *because I can
   make a change and see it when I refresh the browser.

The only thing left, I think, is the other packages.  Are yours different?
We are using:
react & react-dom 17.0.2
react-native-web 0.17.1

--Jerry

**Comment by sschottler** [comment]
Could be - we are on `react-native-web@0.13.7`. You could try downgrading to that version in the fresh repo you setup and see if the patch works. I don't think the react or react-dom versions would matter as much, but we're on `16.14.0`

**Comment by lavor** [comment]
@1jerry @sschottler 
I also came into this issue now (using @ui-kitten@5.1.1) and figured it out.
According to the react-native-web documentation it is necessary to set the `focusable` prop to false (e.g. with patch-package as suggested above).
[The `accessible` prop is not implemented by react-native-web](https://necolas.github.io/react-native-web/docs/accessibility/#keyboard-focus).

**Comment by Andriiklymiuk** [comment]
In my case, i added `outline: 'none', outlineStyle: 'none'` to textStyle to remove outline on safari
