### ISSUE TITLE
Urgent - React native windows build error with dependency on react-native-svg

### ISSUE THREAD

**Issue by manojkumaraut** [akveo/react-native-ui-kitten#1425]
## 🐛 Bug Report
**Facing an issue in react  native windows build error with dependency on react-native-svg** 
![RN](https://user-images.githubusercontent.com/9800500/117661876-8c417480-b1bc-11eb-97d2-e4da292b90f3.png)

## To Reproduce

1. Please make sure the **windows platform** gets added initially and run the below command 
 **react-native run-windows**

## Expected behavior

Need support for windows app platform in react native with UI Kitten components

## UI Kitten and  SVG dependency version

| Package      | Version |
| ----------- | ----------- |
| https://github.com/react-native-svg    |        |
| @ui-kitten/components   |         |

## Environment information

```bash

```

**Comment by Vasault** [comment]
i need an answer to this here, having the same issue on one of my apps

**Comment by artyorsh** [comment]
We don't target windows, and I'd say it was never launched there. So consider this use case experimental.

**Comment by Vasault** [comment]
at least for me it wasn't exactly windows but android, but i solved my issue with a proguard exception rule

**Comment by RWOverdijk** [comment]
This is an issue to be addressed by react-native-svg, which they might already have done since most of us using expo are stuck on version 9. Either way, it's not something ui-kitten has to change to make work.

I think this issue an be closed, with these optional follow-up steps:

1. Does it work with the latest version of react-native-svg? If not, open issue there.
3. If it does work, make sure you're using the latest version in your project.

**Comment by Sumanta9x9** [comment]
This problem won't go away. Use React native paper instead

**Comment by artyorsh** [comment]
UI Kitten packages do not explicitely target old rnsvg version anymore. Ref: https://github.com/akveo/react-native-ui-kitten/pull/1460. For this and for not having Windows as officially supported platform reasons I'm going to close this.

As mentioned by @RWOverdijk, make sure that your app uses latest version of RNSVG package.
