### ISSUE TITLE
Set icon color in Top Navigation based on pimary colour defined in global theme

### ISSUE THREAD

**Issue by dvdprr6** [akveo/react-native-ui-kitten#1475]
## 💬 Question

I have an icon defined in my TopNavigationAction, but the icon colour defaults to white. In my global theme I have set orange as primary colour. How can I configure the TopNavigationAction or Icon to recognize the orange colour I have set in my global theme?

As shown in the screenshot, the bottom tab icons are orange (following the colours I have defined in global theme), I would like to have the same orange colour as the icon in the TopNavigation.

![image](https://user-images.githubusercontent.com/1852283/124848510-0008bf00-df6b-11eb-8c7e-ad7d07816e80.png)

Below is a snippet of the code:

```JavaScript
import React from 'react'
import { Layout, TopNavigation, Icon, TopNavigationAction } from '@ui-kitten/components'


const AppBar = () => {
  return (
    <TopNavigation accessoryLeft={() => <TopNavigationAction icon={props => <Icon {...props} name={'person-add-outline'} />} />} />
  )
}

const FriendsScreen = () => {
  return(
    <Layout style={{ flex: 1 }}>
      <AppBar />
    </Layout>
  )
}

export default FriendsScreen
```
Thanks in advanced!

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.1.0     |
| @ui-kitten/components   |     5.1.0    |

**Comment by artyorsh** [comment]
Hey 👋

There actually are two ways to achieve this:
1. [Configure it with mapping](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping#customize-component-mapping)

Basically you need to override [this variable](https://github.com/eva-design/eva/blob/master/packages/eva/mapping.json#L5798) with `color-primary-default` in mapping file of your app. Also, don't forget about the state colors, at least [active color](https://github.com/eva-design/eva/blob/master/packages/eva/mapping.json#L5807), to achieve a proper touch effect.

2. Override the color with JS

This, however, doesn't solve the problem completely because it's not possible to override the icon color in pressed state. 

```tsx
import { useCallback } from 'react';
import { TopNavigation, TopNavigationAction, Icon, useTheme } from '@ui-kitten/components';

const AppBar = () => {

  const theme = useTheme();

  const renderBackIcon = useCallback((props) => (
    <Icon
      style={[props.style, { tintColor: theme['color-primary-default'] }]}
      name='person-add-outline'
    />
  ), []);

  const renderBackAction = useCallback((props) => (
    <TopNavigationAction icon={renderBackIcon} />
  ), []);

  return (
    <TopNavigation accessoryLeft={renderBackAction} />
  );
};
```
