### ISSUE TITLE
change height celander component 

### ISSUE THREAD

**Issue by amrshadid** [akveo/react-native-ui-kitten#1478]
## 💬 Question

<img width="736" alt="Screen Shot 2021-07-12 at 11 58 50 PM" src="https://user-images.githubusercontent.com/32217515/125354994-2795c800-e36d-11eb-833d-ca85fbecfb3e.png">

How change height celander ?
I can control width but try to change height not work with me ! why  

any idea to slove this issue ? 
| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva             |^2.0.0 |
| @ui-kitten/components   | ^5.0.0 |

**Comment by whitestranger7** [comment]
Hey, @amrshadid. Thanks for your question. **Calendar component doesn't imply height changing for now.**

As workaround you can pass `style={{ height: 'someValue' }}` as prop to Calendar component and try to change style of `renderDay`, `renderHeader` & `renderFooter`.

Since `renderDay` could receive any `React.Element`, you could just scale your cells and move them using `margin` style property.
