### ISSUE TITLE
testID is assigned to both TouchableWithoutFeedback component and TextInput component for the Input component

### ISSUE THREAD

**Issue by iacovlev-pavel** [akveo/react-native-ui-kitten#1490]
## 🐛 Bug Report

Commit #1435  adds a regression, and in my case broke a lot of tests.

`await element(by.id('email')).replaceText('EMAIL');`
This no longer works since testID is now assigned to parent TouchableWithoutFeedback component, this results in replaceText failing.

In the case of the Input component the testID is assigned to both TouchableWithoutFeedback component and TextInput component which makes it extra confusing.

At the moment using Detox I could not find a cross platform way to populate the Input component.

Downgrading to 5.1.0 fixed the issue.

**Comment by AntonBorovoi** [comment]
Hi @iacovlev-pavel 
Could you please provide some examples of the code on how you are passing the testID to the Input component?

**Comment by iacovlev-pavel** [comment]
```
<Input
  label={(itemProps) => (
    <Text numberOfLines={1} {...itemProps}>What&#39;s your email address?</Text>
  )}
  autoFocus
  keyboardType="email-address"
  placeholder="name@example.com"
  textContentType="emailAddress"
  style={styles.email}
  value={formData.email}
  status={!firstSubmit && emailValidate() !== '' ? 'danger' : undefined}
  caption={(!firstSubmit || '') && emailValidate()}
  testID="email"
  onChangeText={(email) => setFormData((prev) => ({ ...prev, email }))}
  onSubmitEditing={handleSubmit}
/>
```

In the test I do `await element(by.id('email')).replaceText('EMAIL');`
In 5.1.1 this results in an error, in 5.1.0 works as expected.

**Comment by manuelmhtr** [comment]
Same on my project. `5.0.0` puts the `testID` in the `TextInput` element (for inputs), while `5.0.1` puts it in the `TouchableWithoutFeedback` element, breaking a ton of tests.

I think the correct behavior is like `5.0.0` since is the Input what is being referenced and is the main component. I would keep it as `5.0.0` and provide a `containerTestID` that puts the `testID` in the `TouchableWithoutFeedback`.

Please share your thoughts and I can send a PR with the changes.

**Comment by AntonBorovoi** [comment]
HiI @manuelmhtr 
From my point of view your solution is pretty good and applicable there.
Would you mind open a PR?

**Comment by longseespace** [comment]
> Same on my project. `5.0.0` puts the `testID` in the `TextInput` element (for inputs), while `5.0.1` puts it in the `TouchableWithoutFeedback` element, breaking a ton of tests.
> 
> I think the correct behavior is like `5.0.0` since is the Input what is being referenced and is the main component. I would keep it as `5.0.0` and provide a `containerTestID` that puts the `testID` in the `TouchableWithoutFeedback`.
> 
> Please share your thoughts and I can send a PR with the changes.

We weren't able to match the `TextInput` even in 5.1.0 (using the native XCTest API, not Detox though). The only way is to set `accessible={false}` for the outer `TouchableWithoutFeedback`

**Comment by sajadghawami** [comment]
Having the same issue.

We are using detox for e2e testing, before a `multiTap` was needed to activate a checkbox. After upgrading, somehow this changed to only one tap and all our tests seem to be broken.

This behaviour also seems to be very flaky, since sometimes two and sometimes only one tap needs to be done.

**Comment by dVaytul** [comment]
@sajadghawami, @longseespace, @iacovlev-pavel, @manuelmhtr 

If we set `testID` on `TextInput` only, would that be more suitable for you or should we keep it in two places both (`TouchableWithoutFeedback`, `TextInput`)?

**Comment by longseespace** [comment]
@dVaytul In our case, we need the `testID` on the `TextInpu` and `accessible={false}` on the `TouchableWithoutFeedback`

**Comment by sajadghawami** [comment]
@dVaytul 

This is my current situation:

Before i did the upgrade, i had `detox@17` and `kitten-ui@5.0.0`

- In one of our test-cases we have multiple inputs and a checkbox that needs to be selected to be able to continue (basic sign-up)
- Before i was forced to use `.multiTap(2)` on the checkbox to firstly release the focus from the last input and to actually be able to check the checkbox

Everything was working fine up until i upgraded, and now this is happening:

- This behaviour seems to have changed, because now i don't have to use `.multiTap(2)` but a single `.tap()` to actually check the checkbox

My problem now is, whenever i run this in our CI, the `.tap()` *does not* work because the focus will still be on the checkbox so it seems like a `.multiTap(2)` is necessary, which on the other hand won't work locally anymore.

I am a little bit desperate at this point, because i (obviously) cleared everything and tried to replicate this locally, but i am not able to. Locally all my tests run like a charm.

i also upgraded to  `detox@19`, `kitten-ui@5.1.1` and even `react-native` and `expo`.

I am not even sure wether or not this is an actual `kitten-ui` problem, or a `detox` problem that i am facing.

(Even if you are not familiar with the api of detox, i think its rather obvious what the tap and multitap does.)


Does anyone happen to have a clue what i could try next?

**Comment by silentsilas** [comment]
Just wanted to say that downgrading to 5.1.0 worked for me. #1473 is also occurring in both 5.1.2 and 5.1.0, though I was able to find the select component by using `by.text('Some Unique Text In Placeholder Prop')`.
