### ISSUE TITLE
How to change border color of select component ?

### ISSUE THREAD

**Issue by kssai-62** [akveo/react-native-ui-kitten#1538]
## 💬 Question

I am unable to show different border colors on different screens for the select component but it is only showing border color according to status unable to show other colors.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^5.1.1    |
| @ui-kitten/components   |    ^2.1.1     |

**Comment by dVaytul** [comment]
Hi @kssai-62 

You can describe your own statuses with different border colours and use them instead of the predefined ones:
- create `mapping.json` with new styles of Select component (see example bellow);
- merge mapping inside `ApplicationProvider`;
- add new status to component: `<Select status="yellow" />`.

For more information [read documentation](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping).

Example of mapping.json (remove comments before using):
```
{
  "components": {
    "Select": {
      "meta": {
        "variantGroups": {
          "status": {  // Add new statuses here
            "yellow": {  // one and more
              "default": false
            }
          }
        }
      },
      "appearances": {
        "default": {
          "variantGroups": {
            "status": {
              "yellow": { // Describe status styles
                "borderColor": "#FFFF00",
                // and other styles: backgroundColor, ...

                "state": { // set styles for different states
                  "focused": {
                    "borderColor": "#CCCC00"
                  },
                  "hover": {
                    "borderColor": "#FFFF00"
                  },
                  "active": {
                    "borderColor": "#FFFF00"
                  },
                  "disabled": {
                    "borderColor": "#FFFFCC"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

```

**Comment by josejimenezbuild** [comment]
How can I set the borderRadius for the select component? maybe without defining a new state. could you give a example
