### ISSUE TITLE
READ THIS BEFORE YOU INSTALL

### ISSUE THREAD

**Issue by zsolt-tracknamic** [akveo/react-native-ui-kitten#1554]
I've used this for almost a year now and here is something to consider before using this:

### Be ready to use unnecessary props passing everywhere.
If the other libraries don't need them this means it can be done without. Now the question is that they made it intentionally like this for no reason or they weren't able to fix it.
Ex. ` 
<Button style={styles.button} status='primary' accessoryLeft={(props) => (
  <Icon {...props} name='star'/>
)}>
      PRIMARY
    </Button>`

### A simple Modal will color your whole console red... and they can't fix it.
See: https://github.com/akveo/react-native-ui-kitten/issues/1094#issuecomment-630141254

### The Input Component has a huge UX issue.
How to reproduce?
**Step 1.** Make a login screen
**Step 2.** Press to fill out the inputs
**Step 3.** Try pressing the Login button while the keyboard is on. (Spoiler: you can't at least on Android)
**Step 4.** Be ready for complaints from the users that they "can't" log in

### Also has the strangest naming system ever met:
When everybody names the property "**clear**", please do not come up with some nonsense like "**ghost**" (Button)
When everybody names the property "**color**", please do not come up with some nonsense like "**status**" (Text, Input, Button)
When everybody names the property "**size**", please do not come up with some nonsense like "**category**" (Text)

Overall is a nice-ish library.
10/10 I will swap out with the first occasion.

**Comment by bnussman** [comment]
lol

**Comment by malashkevich** [comment]
Hello @zsolt-tracknamic and thanks for your feedback. I really appreciate it.

I would like also to explain our decisions, hopefully, it will make sense.

1. Regarding unnecessary pros. The idea behind our components is that every component has a state. So for example button always has a combination of `appearance`, `status` and `size`. But the good thing is that all of them have default values. It's usually mentioned in the docs. So in your example, you can omit `status` because buttons are by default `primary`. 

2. The `InexPath` is the object with `row` and `section` indexes. It's useful when you have groups inside your selection. We don't want to have different APIs for select with and without groups, so there is a little overhead when you don't use groups. But we are open to improvement suggestions.

3. The Modal is a complex thing, and our implementation is far from ideal. We have plans to significantly improve it. But the reason why we haven't done it is just because of the lack of time. It's an open-source library which means it doesn't bring us any money. And sometimes we do not have enough time to fully support it. But, the good thing is that it's open-source, so anyone can do PR to fix/improve it.

4. There are no mandatory Hook usages. You can wrap your component in `withStyles` HOC and you will receive `theme` as a prop.

5. It would be nice if you create a separate issue for the input issue. We definitely need to look into this.

6. Regarding naming:
+ In UI terms there is no such thing as a "clear" button but there is a "ghost" button. (https://uxplanet.org/ghost-buttons-in-ux-design-4cf3717334f8). We decided to use the already known term.
+ Color is pretty straightforward but it's not semantic. UI Kitten does not have any specific color scheme. The color scheme came from Eva Design. And UI Kitten does not rely on exact colors. You can create a color theme where the `danger` color is green, or blue. So we decided on a `status` prop that has semantic meaning and in different schemes will have different values. 
+ Let me explain the difference between `size` and `category`. So in all our components where applicable `size` only affects the number of pixels. But `Text` is different because besides the `fontSize` changes it also change `fontWeight` and `fontFamily` which are not simple pixels size change. This would make inconsistent the system. That's why we introduced `category`.

Anyway, each system has to evolve so we are open to the proposals. You also made me think about our work from a different angle. Thank you :)
