### ISSUE TITLE
Can we use react native ui kitten with nativewind? 

### ISSUE THREAD

**Issue by universegalaxy1112** [akveo/react-native-ui-kitten#1661]
[NativeWind](https://www.nativewind.dev/) uses [Tailwind CSS](https://tailwindcss.com/) as scripting language to create a universal style system for React Native.

Can we mix the library with react native ui kitten? 

If it's possible what's the potential incompatibility?

**Comment by flexbox** [comment]
@universegalaxy1112 yes you can
Here is how you  can mix 2 theme providers (the example is with `@shopify/restyle` but the logic is the same)
https://github.com/akveo/react-native-ui-kitten/issues/1618#issuecomment-1125137347

> what's the potential incompatibility?
I guess you will have some issues with dark mode and probably custom fonts but they are not blockers. You probably will need to wrap your own solution and export again components from UIKitten.

If your problem is solved can you please close the issue? 
It sparks joy for maintainers ✨

**Comment by universegalaxy1112** [comment]
> 

Thank you, @flexbox
