### ISSUE TITLE
It appears that the repository is no longer being updated.

### ISSUE THREAD

**Issue by Jarvie789** [akveo/react-native-ui-kitten#1769]

**Comment by flexbox** [comment]
@Jarvie789 

> no longer being updated
https://github.com/akveo/react-native-ui-kitten/commits/master
From my perspective, it's not the case. 
Open source takes time and resources if you want more velocity maybe you can reach the maintainers to contribute 🚀 

I have the feeling this is more a discussion https://github.com/akveo/react-native-ui-kitten/discussions/1335 rather than an issue.

If your problem is solved can you please close the issue? 
It sparks joy for maintainers ✨
