### ISSUE TITLE
ListView is deprecated and will be removed in a future release

### ISSUE THREAD

**Issue by bsmayer** [akveo/react-native-ui-kitten#353]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

Using RkPicker causes a warning message 'ListView is deprecated and will be removed in a future release'

**Expected behavior:**

Change to FlatList should solve this problem.

**Steps to reproduce:**

Can be reproduced with following react versions.
React: 16.8.3
React Native: 0.59.1 

**Related code:**

```
<RkPicker title={'SELECT'}
               cancelButtonText={'CANCEL'}
               visible={this.state.pickerVisible}
               selectedOptions={this.state.pickedValue}
               data={[this.genreOptions]}
               onConfirm={(value) => this.setState({ pickedValue: value, pickerVisible: false })}
               onCancel={() => this.setState({ pickerVisible: false })} />
```

### Other information:

**OS, device, package version**
```
iOS and Android
```

**Comment by artyorsh** [comment]
Hi @bsmayer, thanks for report!
Will be changed in further release

**Comment by PavelPolyakov** [comment]
hi @artyorsh, will this be updated in v3 ?
I don't see any alternative to this in v4 :(

Plus to this, there is no upgrade guide for upgrading from v3 to v4, or I didn't find it.

It'd be just great, if v3 is still maintained, until there is not feature parity or v4 is superlative.

Regards,

**Comment by artyorsh** [comment]
Hi @PavelPolyakov 

We are not going to maintain v3. And there is no upgrade guide to use v4 because it brings you completely new components and theming system. We will describe this in docs later

In v4 you can use [Popover](https://akveo.github.io/react-native-ui-kitten/docs/components/popover/overview#popover) component to build any modal view with ease.
Furthermore, we're going to build more components in future releases which will also include Pickers.

Thanks for your interest
