### ISSUE TITLE
[Next] How to use next (private dependencies?)

### ISSUE THREAD

**Issue by JCKodel** [akveo/react-native-ui-kitten#355]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description

**Current behavior:**

Trying to use the next branch (because I need TypeScript support), but there are a couple of dependencies that are not public (thus, preventing npm to add the repository):

```
    "@eva/core": "github:akveo/eva#package/core",
    "@eva/processor-kitten": "github:akveo/eva#package/processor-kitten",
```

**Expected behavior:**

Live dangerously on the edge by using a branch marked "next" =P

**Steps to reproduce:**

Tried to `yarn add https://github.com/akveo/react-native-ui-kitten/tarball/next`

### Other information:

**OS, device, package version**
```
Windows 10
```

**Comment by malashkevich** [comment]
Hello @JCKodel.
Thanks for your interest.
Next branch is actually a part of something bigger we call `eva`.
We expect to release this is until the end of Spring.
Unfortunately can't share more at the moment.
You can follow us on [Twitter](https://twitter.com/akveo_inc) in order to stay updated with latest news.

**Comment by andreialecu** [comment]
Also interested in typescript support. Starting a new project and this is kind of blocking. Any ETA?

**Comment by artyorsh** [comment]
@andreialecu 
> We expect to release this is until the end of Spring

**Comment by artyorsh** [comment]
Everyone is now able to check this out :fire:
