### ISSUE TITLE
🌐React Native Web support

### ISSUE THREAD

**Issue by elie222** [akveo/react-native-ui-kitten#456]
### Issue type

I'm submitting a

* [x] feature request

### Issue description

I started playing around with this library with Expo React Native Web. I see it semi works, but there are pieces that don't. For example, in this screenshot the top navigation works, but the bottom doesn't:

![image](https://user-images.githubusercontent.com/3090527/59482088-00a7f780-8e70-11e9-9f97-f92979eefeae.png)

I assume this issue is due to default flex values on web/mobile.

Are there any plans to support Web? Would be happy to contribute too.

**Comment by artyorsh** [comment]
Hi @elie222, thanks for your interest

We had no plans to support react-native-web within this release, but I know this is a trending feature of RN now, so we're going to support this in future releases.

Can you please provide more user experience of using this on web? We would appreciate any feedback 👍

**Comment by elie222** [comment]
So I played around with it a bit more in the last hour.

I found some other pieces also don't work as expected. For example Input:

![image](https://user-images.githubusercontent.com/3090527/59490284-ea5c6480-8e8c-11e9-9d33-2cdffaa1cee7.png)

I tried to get the Kittens demo app working with the recently released Expo Web, but the file paths (`import xyz from '@src/xyz'`) weren't playing nicely with Expo Web. But I imagine there would be a lot of problems to resolve even if I did get it to compile for web as can be seen from the screenshots.

**Comment by artyorsh** [comment]
> import xyz from '@src/xyz'

Unfortunately, we have implemented this incorrectly. This needs to be configured with babel-plugin-module-resolver using aliases inside `babel.config.js`. I can explain the steps of how to get this working if needed

Btw, looks not so ugly for the components that were never tested on the web 😄

**Comment by elie222** [comment]
It's not terrible. The top nav actually works very nicely.
And the tab bar at the bottom does animate the line. The only issue is names lined up vertically rather horizontally. That may be a default flex direction issue.

**Comment by artyorsh** [comment]
> That may be a default flex direction issue

Yes, looks like this. Because `BottomNavigation` component [uses](https://github.com/akveo/react-native-ui-kitten/blob/master/src/framework/ui/bottomNavigation/bottomNavigation.component.tsx#L240) `row` flexDirection

Btw if you're going to continue using UI Kitten in your purposes, we're always welcome any feedback to simplify future react-native-web integration.

Thanks for your reply

**Comment by artyorsh** [comment]
So after some workarounds, we're able now to launch our playground module on a web. For anybody interested in - [here is a sample branch](https://github.com/akveo/react-native-ui-kitten/tree/feat/react-native-web) which should become the start point of integrating UI Kitten with react-native-web.

To launch it, you can simply clone this repo and run `npm i && npm run start:prod`

![image](https://user-images.githubusercontent.com/10753921/59914457-1d6d9d80-9423-11e9-8cf3-d635efd5a2ff.png)

**Comment by artyorsh** [comment]
Did some basic bugfixes which making web components look the same as on mobile. [Changes](https://github.com/akveo/react-native-ui-kitten/commit/6ee049f03298951cba01ff710e25b72ceb29f0bd)

**Problem:**

`StyleSheet.create` is not working properly on react-native-web:
- Reported in https://github.com/necolas/react-native-web/issues/1377.
-  [Demo project](https://github.com/artyorsh/react-native-web-demo#react-native-web-demo)

However, for now we've got a working example for all of implemented components with [some of workarounds I explained](https://github.com/artyorsh/react-native-web-demo/blob/master/src/sample.component.tsx#L38) in a demo project.

**Known issues:**

- TabView crashes because of `PanGestureResponder` which is not currently supported
- TabView scrolling not working (unsupported configuration on a web?)
- Input is not looking well because of a default box styles

**Comment by artyorsh** [comment]
**Update**

- Reduced creating custom styles with an object. Refactored back to StyleSheet as suggested [in answer](https://github.com/necolas/react-native-web/issues/1377#issuecomment-504783801)
- Fixed TabView scrolling

**Issues:**

- ButtonGroup looks not well in `outline`
- Input still needs to remove a box

[Changes](https://github.com/akveo/react-native-ui-kitten/commit/2e23443b8f2a50f4735ef5c8cc1acd8c7ad1baa2)

[Tab View Demo](https://monosnap.com/file/gljeOfEDXraeoQG78iug0FrIz0YQig)

**Comment by rdewolff** [comment]
The links with the demo are not working, do you have them by any chances?
