### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by betoharres** [akveo/react-native-ui-kitten#46]
Maybe I'm the dumbest person in the world, but I could not figure out how to use the library the same way as it was shown in the demo. In the "Documentation" section of the website shows a clear limited options compared to the many different(cool) components in the "Demo", like List Menu, Progress Bar, Walkthrough, etc... 
What am I missing? Thanks in advance, great library <3 looking foward to use in my next app!

**Comment by malashkevich** [comment]
Hi @betoharres.
Our demo is showing examples of `react-native-ui-kitten` usage.
We don't include all components from demo in our library because they are easy to build using our lib.
Demo app sources you can find here https://github.com/akveo/kittenTricks
Just look at sources, copy what you need, adjust styles and you will have the same UI.

Does it helps?

**Comment by betoharres** [comment]
Thanks a lot @malashkevich I will check it out later today, if I have any more questions I will reopen this issue, thanks again! 🎉 👍

**Comment by gerard080395** [comment]
@betoharres Hi,
Did you manage to use the library finally ?
Because I'm still having troubles using the documentation.
The documentation says we should configure the application root but i can't figure out which file it relates to.
Is it the App.js ? if yes how to do the connection later on ?
@malashkevich I would be glad if there was a basic configuration tutorial someone could link me too. Because there is actually nothing on the internet except the documentation which has not really helped me.

Thanks in advance

**Comment by artyorsh** [comment]
@gerard080395 In most cases when you start a project with react-native or expo CLI with 
`react native init PROJECT_NAME` or `expo init PROJECT_NAME` you will have an `App.js` file which is meant to be your `application root` as we describe in documentation

So yes. You need to use `ApplicationProvider` exact in that file

**Comment by gerard080395** [comment]
@artyosh thanks for the help

**Comment by betoharres** [comment]
Hi @gerard080395 I never got into the library, I don't know why, but the library looks very interesting, hope you get along well with the lib!

**Comment by gerard080395** [comment]
Sorry for bothering you guys again.I finally managed to get the library working in my react-native project.
@artyorsh I'm having some issues with using the demo examples.
the SignInForm1Component.tsx for example make used of @kitten/theme which is never mentionned in the documentation.
What is it referring to ?

**Comment by artyorsh** [comment]
@gerard080395 you should change any `@kitten/theme` and `@kitten/ui` imports to `react-native-ui-kitten`

**Comment by anhnch** [comment]
> Maybe I'm the dumbest person in the world, but I could not figure out how to use the library the same way as it was shown in the demo. In the "Documentation" section of the website shows a clear limited options compared to the many different(cool) components in the "Demo", like List Menu, Progress Bar, Walkthrough, etc...
> What am I missing? Thanks in advance, great library <3 looking foward to use in my next app!

I don't see the Progress Bar in the demo. Where is it, btw?
