### ISSUE TITLE
How to customize input padding

### ISSUE THREAD

**Issue by Gitldx** [akveo/react-native-ui-kitten#568]
On low-resolution Android phones, the space between text and borders is too big.
I tried the following changes, but they didn't work.

<Input
              style={{paddingVertical:0}}  //here is my own style
              textStyle={textStyle.paragraph}
              placeholder='Message...'
              onChangeText={this.onNewMessageChange}
 />

**Comment by artyorsh** [comment]
Hi 👋 
Try passing paddings into `textStyle` prop

**Comment by Gitldx** [comment]
Hi～This works partially,but even when I set padding Vertical to 0, the space between text and border still exists, and I try to set marginVertical = 0, it doesn't get smaller.Any way , it has improved a lot now. It would be better if space could be completely eliminated.Thank you very much. By the way, textStyle's statement is somewhat misleading, and it's not clearly explained in the document.

**Comment by Acetyld** [comment]
Yhea they should 100% fix this.
I ended up with this "fix" 
textStyle={{paddingVertical:10,marginLeft:-5,paddingLeft:10,marginRight:0,fontSize:15}}
size='small'

Using small to make padding as less as possible and then repositining the view according to the button.

The padding thing is a REAL problem on phones. Because it makes the inputs pretty hard to press!
