### ISSUE TITLE
Themes need a lot more customisation

### ISSUE THREAD

**Issue by mtimofiiv** [akveo/react-native-ui-kitten#569]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x] feature request

### Issue description

From what I read of the docs, it is not possible to uniformly style things beyond some basic colour settings. I understand that Kitten is a "design system" and not just a collection of themed components, and I think it looks + works great (and I love these components), but I am really lacking some functionality in the styling department.

Why can't themes include additional parameters like font families? [react-native-elements](https://react-native-training.github.io/react-native-elements/docs/customization.html) does a nice job of this with their UI kit. Right now if I want to do that, I'm stuck with forking your repo!

I think the individual params have been discussed before in open/closed issues but I just want to ask in general the methodology behind only making colours editable.

And yes, I'm aware that you can style components individually, but to be honest it's not great for me. That means that I have to create my own component called `Button` and wrap it around your button so I can apply just a few style changes to it.

**Comment by artyorsh** [comment]
Hi @mtimofiiv 👋 

Thanks for the question, there are a lot of good points mentioned :)

**Font Families:** We don't currently explicitly set it, because the final app bundle will crash if it doesn't contain fonts linked in ios and android projects. We still looking for a good solution to do this. You can see [how we solve this in Kitten Tricks](https://github.com/akveo/kittenTricks/blob/next/src/components/common/style.ts#L1), but I hope we can find a better approach in future

**Rest global properties:** Eva also can export global configuration properties like `roundness` to set a global borderRadius, like it is implemented in react-native-paper. But you're right about we're the part of the design system, and we also have another framework working with Eva, so these changes should be discussed between teams, and could take a lot of time to implement fully synchronized stylings :)

Thanks for your interest. You can also create a discussion issue in [Eva Design System repo](https://github.com/eva-design/eva).

**Comment by mtimofiiv** [comment]
Hi @artyorsh, thanks for your quick answer! 😘

> Font Families: We don't currently explicitly set it, because the final app bundle will crash if it doesn't contain fonts linked in ios and android projects. We still looking for a good solution to do this. You can see how we solve this in Kitten Tricks, but I hope we can find a better approach in future

Thanks for the tip, I might do this in the short term!

> Other global properties: Eva also can export global configuration properties like roundness to set a global borderRadius, like it is implemented in react-native-paper. But you're right about we're the part of the design system, and we also have another framework working with Eva, so these changes should be discussed between teams, and could take a lot of time to implement fully synchronized stylings :)

I get that!

> Btw, can you please explain with a bit more details what other styling functionality you're missing or unable to use?

For me font family is important at this stage, and I can't think of anything else that colours and roundness has not covered. I would imagine pretty much everything else is more something you do on an individual component basis.

> You can also create a discussion issue in Eva Design System repo.

I can do that!

**Comment by artyorsh** [comment]
@mtimofiiv 
One more option you can do here is to [customize Eva mapping](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping#determine-a-change). I've also [created an example](https://gist.github.com/artyorsh/dc4554404ddbd8d990c2f707fd125838) of how you can achieve this

**Comment by 592da** [comment]
@artyorsh thanks for the example,
since I use a custom font, this not applied to different font weights... 
so I need to set fontFamily to each component which is not text like Button, Input, etc.
how do I set different font family to Button component or any other component that has textStyles mapping?
thanks

**Comment by artyorsh** [comment]
@592da You can use Eva mappings in the same way like we do it for Text component. Also, in case of styling `Button` or `Input` you're still able to use `textStyle` property to pass your `fontFamily`

**Comment by 592da** [comment]
@artyorsh thanks for your reply :)
I tried to do that but no success... any example, please?

**Comment by artyorsh** [comment]
@592da just realized this will require changes in component implementation, so please use `textStyle` props currently. We're sorry about disinformation and going to fix this in a future releases

**Comment by 592da** [comment]
thanks @artyorsh, appreciate your great work! 

BTW, the preferred way to ask a question related to this repo is open an issue?

If I want to use `react-native-masked-text` for example, and make use of the current input component, so basically all I need to do is replace the underlying text input component from the native one to the new one, how should I do that ? I tried to duplicate the input component and only change the text component with `styled<InputProps>(InputMask);` but no success.

any thoughts ?

**Comment by artyorsh** [comment]
> BTW, the preferred way to ask a question related to this repo is open an issue?
Yes :) Please open the new one so we can move there
