### ISSUE TITLE
[RkChoise] contentStyle properties fail if setting 'color'

### ISSUE THREAD

**Issue by kay-es** [akveo/react-native-ui-kitten#58]
Hey guys,

first of all, thanks for your great ui library!

I want to change the content color of a clear RkChoice-Component.

```
<RkChoice contentStyle={{color: '#000'}} rkType='clear' selected={[TRUE|FALSE]}/>
```

But the color property is not set directly on the Text element rather on the enclosing View element.
The following warning appears:

> Warning: Failed prop type: Invalid props.style key `color` supplied to `View`.
> Bad object: {
>   "width": 26,
>   "height": 26,
>   "justifyContent": "center",
>   "alignItems": "center",
>   "color": "#000"
> }
> Valid keys: [
>   "display",
>   "width",
> ...

Maybe you can tell me if this is a bug of ui-kitten or if I make any mistakes.

Thanks and regards
Kay

**Comment by sergey-kozel** [comment]
Hi @kay-es,

Indeed, there is hard enough to understand how to customize of this component. By default 'clear' rkType is rendered as `<View><Image/></View>` and your contentStyle is applied to `<View>`. Therefore you got this warning. Unfortunately, there is no possibility to customize RkChoice to change just color of mark. If you want do that you need to define your own 'content' property for 'inner' component and render it as you wish:
```
  RkTheme.setType('RkChoice', 'yourType', {
    inner: {
      content: (<View><Image source={require('yourMark.png')}/></View>)
    }
  });
```
We are going to refactor this component in order to make it more straightforward for customization.
