### ISSUE TITLE
Use System Font?

### ISSUE THREAD

**Issue by bluetidepro** [akveo/react-native-ui-kitten#62]
This may be a silly question but how do I just have my theme use the default system font (_`San Francisco` on iOS, and `Roboto` on Android_)? Do I need to set that in my `theme.js` file? Or does that just happen automatically if I don't set any font?

**Comment by sergey-kozel** [comment]
Hi @bluetidepro,

There is no FontFamily setting in theme by default. And we do not change any font settings in RkComponents except font size by default. So, you don't need to do anything to use the default font of your environment. Pay attention to "enviroment" word because if you just put your RkComponent to some View then default font will be 'System', but if you have the following hierarchy:
```
        <Text style={{fontFamily: 'AwesomeFont'}}>
          Hello from Text!
          <RkText>Hello from RkText!</RkText>
        </Text>
```
then the default fontFamily for RkText will be 'AwesomeFont' too.
If you want to set fontFamily for your RkComponent explicitly you can create RkType where you can specify desired style settings for an appropriate internal component of RkComponent. For example for RkText and RkTextInput:
```
  RkTheme.setType('RkText', 'System', {
    text: {
      fontFamily: 'System',
    }
  });

  RkTheme.setType('RkTextInput', 'AwesomeFont', {
    input: {
      fontFamily: 'AwesomeFont',
    }
  });
```
If you want you can add 'fontFamily' parameter to a theme as well as any other parameter you want to change through themes management:
```
  RkTheme.setTheme({
    myParameters: {
      myDefaultFont: 'System',
      myAwesomeFont: 'AwesomeFont'
    },
  });

  RkTheme.setType('RkText', 'basic', {
    text: {
      fontFamily: theme => theme.myParameters.myDefaultFont
    }
  });

  RkTheme.setType('RkText', 'awesome', {
    text: {
      fontFamily: theme => theme.myParameters.myAwesomeFont
    }
  });
```
