### ISSUE TITLE
The app crashes when using new Hermes engine

### ISSUE THREAD

**Issue by johanquiroga** [akveo/react-native-ui-kitten#664]
### Issue type

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

The app crashes when using new Hermes engine.

This only happened once I added the Icons Module, before that the app was working correctly with the Hermes engine.
![Screenshot_1570497400](https://user-images.githubusercontent.com/22845267/66360302-3782ab80-e940-11e9-9fde-ec69e682d16f.png)

**Expected behavior:**

The app works with or without the Hermes engine.

**Steps to reproduce:**

### Other information:

**OS, device, package version**

```
"@eva-design/eva": "^1.2.0"
"@ui-kitten/eva-icons": "^4.2.0"
"react-native": "0.61.1"
"react-native-ui-kitten": "^4.2.0"
```

**Comment by artyorsh** [comment]
Hi @johanquiroga 👋 
I guess this is mostly not a framework issue, just because Hermes engine does not currently support Proxies. [See the related thread](https://github.com/facebook/hermes/issues/33)

And yes, this is because Icons module relies on Proxies, but this was the simplest solution for us. Btw, MobX users [have the same issues](https://github.com/facebook/hermes/issues/33) with Hermes.

**Comment by anhtuank7c** [comment]
I think we should use module `proxy-polyfill` for this line:
https://github.com/akveo/react-native-ui-kitten/blob/05a3471c49916e8bdf8f7caaf3070b409582025e/src/eva-icons/createIconsMap.ts#L7

ie:
```javascript
import PolyfillProxy from 'proxy-polyfill/src/proxy'

...
return new PolyfillProxy({}, {...})
```

**Comment by artyorsh** [comment]
@anhtuank7c does it resolves an issue?

**Comment by artyorsh** [comment]
@anhtuank7c I did some review on this now, and what I get is that we don't get application crashes, but for any reason it's unable to find requested property, e.g:
```
const HeartIcon = () => <Icon name='heart' />
```

will lead to runtime error of `@ui-kitten/eva-icons` package saying 'heart' does not exist

**Comment by AndreaTurco** [comment]
Hi all
In my case, this issue is present only on android and my currently workaround is :

- use the solution showed by @anhtuank7c 
- removed all the `import { Icon } from '@ui-kitten/components';` and use:
```
import React from 'react';
import { Image } from 'react-native';
import { Button } from '@ui-kitten/components';

const RemoteBulbIcon = (style) => (
  <Image
    style={style}
    source={{ uri: 'https://akveo.github.io/eva-icons/outline/png/128/bulb-outline.png' }}
  />
);

export const IconExternalSourceShowcase = (props) => (
  <Button icon={RemoteBulbIcon}>
    Login with Facebook
  </Button>
);
```
icons from: (https://akveo.github.io/eva-icons/#/)

Other information:
OS, device, package version:
```
    "@eva-design/eva": "^1.3.1",
    "@ui-kitten/eva-icons": "^4.3.2",
    "react-native-ui-kitten": "4.3.2",
```

**Comment by artyorsh** [comment]
@AndreaTurco the reason is that Hermes engine doesn't support proxies. This engine is used to increase Android performance, and it doesn't affect iOS in total. Currently we have no workaround to get rid of proxies, so if you really need Hermes - your solution would work, but will affect UX because of loading icons remotely instead of using SVGs.

**Comment by anhtuank7c** [comment]
Good news ever!!!!

https://twitter.com/HermesEngine/status/1245136667414913024

<img width="589" alt="Screen Shot 2020-04-02 at 21 07 34" src="https://user-images.githubusercontent.com/3163410/78258839-fef61000-7525-11ea-88d0-1c14e261ba8b.png">

**Comment by artyorsh** [comment]
@anhtuank7c thanks for sharing 👍

**Comment by lewatt23** [comment]
@anhtuank7c  Please any workaround? am using react-native 0.62  but I still have this error...

**Comment by anhtuank7c** [comment]
@lewatt23 Did you try `npm install hermes-engine@v0.4.2-rc1`?

**Comment by lewatt23** [comment]
@anhtuank7c My bad thought I was installed by default since I was using rn 0.62.2, just installed and is working fine, thanks :)

**Comment by ashishfeels** [comment]
for those using 0.63 use npm install hermes-engine@v0.5.2-rc1

**Comment by santiago1393** [comment]
> for those using 0.63 use npm install hermes-engine@v0.5.2-rc1

It worked after clean gradle builds
Thanks!!

**Comment by kuasha420** [comment]
0.64 will have Proxy enabled by default on Hermes. Woohoo!

**Comment by teamzz111** [comment]
> for those using 0.63 use npm install hermes-engine@v0.5.2-rc1

Workssss
