### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by veedeo** [akveo/react-native-ui-kitten#696]
What is the way to implement simple autocomplete using this library. Something like Select component but with editable input inside?

**Comment by artyorsh** [comment]
Just look through `Input` and `Select` sources. It has a similar box, but Input also contains `TextInput` component in a render tree. By combining Input and Select you can achieve needed behavior.

**Comment by artyorsh** [comment]
@veedeo You also might be interested in using [this guide](https://akveo.github.io/react-native-ui-kitten/docs/design-system/custom-component-mapping#prepare-the-boilerplate) to use custom mappings. But since autocomplete is something similar to `Select`, you may need simply copy mappings for this component

**Comment by aleqsio** [comment]
One thing that is missing a bit from this library switching from material-ui is the ability to easily customize behavior by injecting custom components to switch out the default ones (like passing an input prop to select https://material-ui.com/api/select/).

I've looked at changing the select component to display an <Input> in place of text, but i'd have to either fork this library, copy the entire Select component to my codebase, importing internal files that could change at any point, or use some sort of monkey patching techniques to achieve this. Is there an easier solution?

I think adding the ability to specify custom render functions via passing props (so we could provide a custom renderControlChildren function and be able to easily combine different building blocks provided by ui-kitten) would be very useful. The customizable theming solution works wonderfully, but i find that the ability to customize behavior is a bit underwhelming.

**Comment by artyorsh** [comment]
@aleqsio Thanks for the detailed answer. Our main goal for the v4 release was to fit [Eva Design System](https://eva.design) specifications. The customization features still not in our backlog, but I guess we can improve UI Kitten with features you described in future releases since it really makes sense 👍 

Did you able to migrate from material-ui to UI Kitten?

**Comment by artyorsh** [comment]
In my opinion, we've built something restrictive out of the box, but you have a lot of predefinded parameters like `status`, `size` or `appearance` to customize components for your needs. But if you like something really custom or branded for your product, you basically able to do this with our [styling system](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping#customize-component-mapping) and Eva Design System tools (e.g [Color generator](https://colors.eva.design)). It's kinda complex when you start from a scratch, but it's really powerful (our company was already able to finish several outsource projects)

Thanks for the feedback!

**Comment by sudomann** [comment]
@artyorsh thank you for mentioning that color generator, did not know that existed! Previously I was inspecting source code for eva package to update color mappings accordingly. Not a fun process  :(
