### ISSUE TITLE
How to add shadow in <Card/>?

### ISSUE THREAD

**Issue by rosnaib11** [akveo/react-native-ui-kitten#851]
I'm trying to implement similar effect like this,

![image](https://user-images.githubusercontent.com/26837762/73158919-39a38c80-4120-11ea-995a-821329c1d8d0.png)

```
<Card style={{
            backgroundColor:"white", 
            padding: 0, 
            borderRadius: 10, 
            shadowOffset: {width :10, height: 10}, 
            shadowColor: "black", 
            shadowOpacity: 0.50,  
            margin: 0}} 
          header={false}
          >
 ...
```

**Comment by artyorsh** [comment]
Your code will not work on android since `shadowOffset` and other `shadow` props are iOS-specific in React Native. Our documentation runs Angular application, and the card you're looking for is a part of [Nebular framework](https://github.com/akveo/nebular), not UI Kitten.

You may try using [3rd party libraries](https://github.com/879479119/react-native-shadow) for building cross-platform shadows.
