### ISSUE TITLE
Switch custom mapping when user click button

### ISSUE THREAD

**Issue by sovannvin** [akveo/react-native-ui-kitten#881]
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

**Comment by artyorsh** [comment]
You're not able to do this during the runtime

**Comment by sovannvin** [comment]
> You're not able to do this during the runtime. Prefer using themes in order to do this

Well, I just want to switch text font but can I use it using them ?

**Comment by artyorsh** [comment]
Officially - no, but you can put custom variable into your theme object, e.g:
**font-1-theme.js**:
```
{ "font-family-variable-name": "font-1" }
```

Same for second theme

And then use the name of this variable in your custom mapping (I'm not sure but you may need to replace all `text-font-family` variables with `font-family-variable-name`

Use it on own risk, because this is not official way of doing such customization :)
