### ISSUE TITLE
Undefined is not an abject (evaluating _reactnativeuikitten.RkTheme

### ISSUE THREAD

**Issue by Subramani058** [akveo/react-native-ui-kitten#905]
Hi,
I just upgrade my react-native version to latest and also packages associate with that. I upgrade react-native-ui-kitten version  from 3.0.1 to 4.3.2 there is error will show relate to UI kitten. So can u provide the proper documentation for changing project version from 3.0.1 to 4.3.2. And also i have different theme for different entity in my project.

**Comment by artyorsh** [comment]
@Subramani058 v3 is not compatible with v4 as it was completely rewritten and there is no migration guide for this.

**Comment by Subramani058** [comment]
Can i upgrade to latest react-native version with react-native-ui-kitten@3.1.4. Will it support?

**Comment by artyorsh** [comment]
Depends on what version of react-native you're installing.
We don't maintain v3 since react-native 0.57, so you should see if react-native brings any breaking changes starting from that version. It's changelog is [here](https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#057).
