### ISSUE TITLE
How to customize navigation tint colors from react-navigation

### ISSUE THREAD

**Issue by allpwrfulroot** [akveo/react-native-ui-kitten#909]
## How to customize BottomTabBar tint colors? 

I can manually override indicator, icon, and title colors separately, but this seems extraordinarily kludgy. What's the proper way of changing the default active/inactive tint colors for navigation components (using react-navigation, ideally the activeTintColor/activeTintColor tabBarOptions)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    1.4.0    |
| @ui-kitten/components   |   4.4.1      |

**Comment by artyorsh** [comment]
> I can manually override indicator, icon, and title colors separately, but this seems extraordinarily kludgy.

As a maintainer I would say it will until you start using colors as it is described in [Branding guide](https://akveo.github.io/react-native-ui-kitten/docs/guides/branding). 
And here is why - UI Kitten is a Design System based library, and it will never have active/inactive/whateverElseStateColor properties because it will make it a hell.
