### ISSUE TITLE
Button Text Clipping

### ISSUE THREAD

**Issue by pedromoter** [akveo/react-native-ui-kitten#918]
## 🐛 Bug Report

Hello, I am trying to render larger text inside a button, but when it renders it clips the text in half. I have tried changing properties such as size and margin, but the render still getting cut both in IOS and Android

## To Reproduce

Use code below 

    <Button style={{ width: '80%',borderRadius: 15, position : 'absolute', bottom : '10%'}} textStyle={{ fontSize: 20, textAlignVertical: 'center', marginTop: 10}}   >
    Get Started!
    </Button>

## Expected behavior

<img width="400" alt="Screen Shot 2020-02-29 at 11 37 25 AM" src="https://user-images.githubusercontent.com/10541029/75611396-2d786980-5ae8-11ea-8e1f-01f8069f62a9.png">

**Comment by artyorsh** [comment]
Hi! You need to set `lineHeight` by passing it to `textStyle` prop if you would like to increase it. Because it is provided by Eva by default. I also recommend you setting it by costomizing mapping. See default values [here](https://github.com/eva-design/eva/blob/master/packages/eva/mapping.json#L5)

**Comment by pedromoter** [comment]
Thank you so much!
