### ISSUE TITLE
Loading data on screen load

### ISSUE THREAD

**Issue by mkj-git** [akveo/react-native-ui-kitten#939]
I have following code, Right now `renderProductItem` is rendered with fixed `products`. I want list to be rendered on screen load. So when screen is loaded it should call an API and render the list based on API response. 

I saw solutions using `state` sopmething like https://github.com/vikrantnegi/react-native-searchable-flatlist/blob/master/src/SearchableList.js but the problem is when i create `constructer` its not getting called on screen load. So i am not sure how to use `state` in my case.

I am unable to figure out how to call an API on screen load and render list once response is available.
   
    export const ProductListScreen = ({ navigation, route }): React.ReactElement => {   
   
      const displayProducts: Product[] = products.filter(product => product.category === route.name);    
      
      const renderProductItem = (info: ListRenderItemInfo<Product>): React.ReactElement => (
        <Card
          style={styles.productItem}
          header={() => renderItemHeader(info)}
          footer={() => renderItemFooter(info)}
          onPress={() => onItemPress(info.index)}>
          <Text category='s1'>
            {info.item.title}
          </Text>
          <Text
            appearance='hint'
            category='c1'>
              {info.item.category}
          </Text>
              <RateBar
                style={styles.rateBar}
                value={4}
              // onValueChange={setRating}
              />
          <CategoryList
            style={styles.categoryList}
            data={["Adventure", "Sport", "Science", "XXX"]}
          />
          <Text>
            The element above represents a flex container (the blue area) with three flex items.
          </Text>
        </Card>
      );
    
      return (
        <List
          contentContainerStyle={styles.productList}
          data={displayProducts.length && displayProducts || products}
          renderItem={renderProductItem}
        />
      );
    };

**Comment by artyorsh** [comment]
You use function components, where state property not work. You should use [useState](https://reactjs.org/docs/hooks-state.html)

**Comment by mkj-git** [comment]
I tried using ` componentDidMount() { } ` like below:

```
export const ProductListScreen = ({ navigation, route }): React.ReactElement => { 

   componentDidMount() {
    this.makeRemoteRequest();
  }

  makeRemoteRequest = () => {
    const url = `https://randomuser.me/api/?&results=20`;
    this.setState({ loading: true });

    fetch(url)
      .then(res => res.json())
      .then(res => {
        this.setState({
          data: res.results,
          error: res.error || null,
          loading: false,
        });
        this.arrayholder = res.results;
      })
      .catch(error => {
        this.setState({ error, loading: false });
      });
  };
```

i am getting `Cannot find name 'componentDidMount'.`. How can I use `componentDidMount` and `state` together inside `ProductListScreen` ?

**Comment by artyorsh** [comment]
You use component class api in function components. This will not work. In function components you should [use hooks](https://reactjs.org/docs/hooks-intro.html) instead of lifecycle methods like `componentDidMount`.

The example you're interested in is in [docs](https://akveo.github.io/react-native-ui-kitten/docs/components/spinner/examples#spinner)

**Comment by sergiomaciel** [comment]
** use hooks**
`
// all Impots
import React, {useState, useEffect} from 'react';


function useDemo(){
  const [products, setProducts] = useState([]);
  
   //Function call api
  const api = () =>  apiProducts.getList()
  .then((response) => {
    if (response.ok) {
      setProducts(response.data);
      console.log('Status API:'+ response.status)
    } else {
      console.log('ERROR API:'+ response.status)
    }    
  });

 // replaces a componentDidMount
 // use true or a value that if it changes the hook is executed again, 
 //it can also be an id in the case of searching for a product.
 //Otherwise it would enter an infinite loop
  useEffect(()=>{
    api();
  },[true])

  return products;
};

export const ProductListScreen = ({ navigation, route }): React.ReactElement => {   

  const displayProducts = useDemo();    
  
 
  return ();
};
`
