### ISSUE TITLE
Autocomplete popover is hidden under modal

### ISSUE THREAD

**Issue by AnasAlamin** [akveo/react-native-ui-kitten#948]
## 🐛 Bug Report

the popover of Autocomplete is hidden under React native Modal and unseen,
also, it's particularly covering the input on Android 
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

## Environment information

```bash

```

**Comment by artyorsh** [comment]
> the popover of Autocomplete is hidden under React native Modal and unseen

UI Kitten relies on its own implementation of modal

> it's particularly covering the input on Android

I guess, it's the height of the status bar. You should configure it. See related discussion #743

**Comment by AnasAlamin** [comment]
> > the popover of Autocomplete is hidden under React native Modal and unseen
> 
> UI Kitten relies on its own implementation of modal
> 
> > it's particularly covering the input on Android
> 
> I guess, it's the height of the status bar. You should configure it. See related discussion #743

Sorry but what do you it relies on its own implementation of modal... Could you please explain more?

**Comment by artyorsh** [comment]
[This modal](https://akveo.github.io/react-native-ui-kitten/docs/components/modal/overview)

However, this issue might be a stopper for you now or might require finding a workaround because of [this issue](#826).
Rendering inside RN modal is discussed [here](https://github.com/akveo/react-native-ui-kitten/issues/945) and probably will be available as feature soon.

We're sorry for such type of issue, and if you find a workaround for that, please post it here for users who also can be interested in this. Thanks

**Comment by fireridlle** [comment]
@artyorsh unfortunately  modal from @ui-kitten/components doesn't support animation like native does

**Comment by artyorsh** [comment]
@fireridlle that’s why this is on our plan🚀
