### ISSUE TITLE
How to override list component's spacings

### ISSUE THREAD

**Issue by RWOverdijk** [akveo/react-native-ui-kitten#956]
## 💬 Question

How can I override the spacing between the title and the description within the ListItem? Our designer changed the space line-height between them to 8, but I don't see an option for that in the mapping.

And on that note a follow up question: How can I override mapping values? Should I just add the same path in my custom mapping and will it then override the default mapping?

Thanks again, I'm having a blast working with this system! 😄

**Comment by artyorsh** [comment]
> How can I override the spacing between the title and the description within the ListItem?

I suppose with mapping? If yes 👇 

> How can I override mapping values?

We have no detailed guide on it, except [this](https://akveo.github.io/react-native-ui-kitten/docs/design-system/customize-mapping), because to be honest now it is a limitation of mappings - it is not strongly typed.
You may take a look on the original [mapping.json](https://github.com/eva-design/eva/blob/master/packages/eva/mapping.json) and see how ListItem uses it.
You may override any existing value that is listed in `parameters`.

You can also do this inline, with `titleStyle` or `descriptionStyle`. But I guess this is not an option.

**Comment by RWOverdijk** [comment]
@artyorsh I guess I'll _have to_ use the inline styles then because there's no option to just separate them a bit further... Ah well. Thank you!

**Comment by artyorsh** [comment]
@RWOverdijk as an option, you can use different line height for title / description. It is declared in [parameters](https://github.com/eva-design/eva/blob/master/packages/eva/mapping.json#L3278) and [uses subtitle-2 mappings](https://github.com/eva-design/eva/blob/master/packages/eva/mapping.json#L3336). You can use explicit values
