### ISSUE TITLE
Change DatePicker to native wrapper for @react-native-community/datetimepicker

### ISSUE THREAD

**Issue by nstranquist** [akveo/react-native-ui-kitten#980]
## 🚀 Feature Proposal

I suggest that rather than create own date time picker, to do what other ui libs do and create a wrapper around the community-supported library that helps create native android/ios datetime pickers

## Motivation

I believe this will let the library create a more effective, supported, aesthetically superior datetime picker interface.

## Example

https://wix.github.io/react-native-ui-lib/docs/DateTimePicker/

**Comment by nstranquist** [comment]
(compared to existing: https://akveo.github.io/react-native-ui-kitten/docs/components/datepicker/overview#rangedatepicker)
Almost forgot to say, I love this library! Thank you for all of the great work,

**Comment by artyorsh** [comment]
@nstranquist thanks for a proposal and warm words <3

However, I don't think this is a good idea because it will break the main concept of this library. It is design system based and we try to solve UI cases relying on our own implementation to bring a new, fresh solution. Relying on existing solutions will break it, since (in case of picker) it will use Material Design on Android and Apple Design on iOS.

Also, there are tons of good working wrappers for this component :) I also have it and can share the gist if you're interested.

**Comment by lesmo** [comment]
Plus it'll probably break the ongoing effort of supporting `react-native-web`. It's a problem maintaining three platforms (Android, iOS and Web), now imagine maintaining whatever number of screens you have times three (because each would have a different design and dimensions).
